// string.scaly

struct scaly_dot_string {
stringstringPagepointercharpointerstringlengthstrlencstringpackedLengthgetPackedLengthlengthbufferpointerstringpage_dot_allocateObjectpackedLength+lengthwritePackedLengthbufferlengthcopyNativeStringcstringbuffer+packedLengthlengthbuffer}
