// Syntax types generated from scaly.sgm
// DO NOT EDIT - generated by codegen

export interface Span {
  start: number
  end: number
}

export interface IdentifierLiteral extends Span {
  _syntax: 'IdentifierLiteral'
  name: string
}

export interface StringLiteral extends Span {
  _syntax: 'StringLiteral'
  value: string
}

export interface CharacterLiteral extends Span {
  _syntax: 'CharacterLiteral'
  value: string
}

export interface FragmentLiteral extends Span {
  _syntax: 'FragmentLiteral'
  value: string
}

export interface IntegerLiteral extends Span {
  _syntax: 'IntegerLiteral'
  value: string
}

export interface BooleanLiteral extends Span {
  _syntax: 'BooleanLiteral'
  value: boolean
}

export interface FloatingPointLiteral extends Span {
  _syntax: 'FloatingPointLiteral'
  value: string
}

export interface HexLiteral extends Span {
  _syntax: 'HexLiteral'
  value: string
}

export type Literal =
  | StringLiteral
  | CharacterLiteral
  | FragmentLiteral
  | IntegerLiteral
  | BooleanLiteral
  | FloatingPointLiteral
  | HexLiteral

export interface ThrownSyntax extends Span {
  _syntax: 'ThrownSyntax'
}

export interface ReferenceSyntax extends Span {
  _syntax: 'ReferenceSyntax'
  location: string
}

export interface LocalSyntax extends Span {
  _syntax: 'LocalSyntax'
}

export interface CallSyntax extends Span {
  _syntax: 'CallSyntax'
}

export type LifetimeSyntax =
  | CallSyntax
  | LocalSyntax
  | ReferenceSyntax
  | ThrownSyntax

export interface ExtensionSyntax extends Span {
  _syntax: 'ExtensionSyntax'
  name: string
}

export interface NameSyntax extends Span {
  _syntax: 'NameSyntax'
  name: string
  extensions: ExtensionSyntax[] | null
}

export interface TypeSyntax extends Span {
  _syntax: 'TypeSyntax'
  name: NameSyntax
  generics: GenericArgumentsSyntax | null
  optional: OptionalSyntax | null
  lifetime: LifetimeSyntax | null
}

export interface IsSyntax extends Span {
  _syntax: 'IsSyntax'
  name: NameSyntax
}

export interface SizeOfSyntax extends Span {
  _syntax: 'SizeOfSyntax'
  type: TypeSyntax
}

export interface SetSyntax extends Span {
  _syntax: 'SetSyntax'
  target: OperandSyntax[]
  source: OperandSyntax[]
}

export interface OperationSyntax extends Span {
  _syntax: 'OperationSyntax'
  operands: OperandSyntax[]
}

export type ActionSyntax =
  | OperationSyntax
  | SetSyntax

export interface RepeatSyntax extends Span {
  _syntax: 'RepeatSyntax'
  name: LabelSyntax | null
  action: ActionSyntax
}

export interface LabelSyntax extends Span {
  _syntax: 'LabelSyntax'
  name: string
}

export interface ForSyntax extends Span {
  _syntax: 'ForSyntax'
  variable: string
  annotation: TypeAnnotationSyntax | null
  operation: OperandSyntax[]
  name: LabelSyntax | null
  action: ActionSyntax
}

export interface LambdaSyntax extends Span {
  _syntax: 'LambdaSyntax'
  input: OperandSyntax[]
  block: ActionSyntax
}

export interface ThrowSyntax extends Span {
  _syntax: 'ThrowSyntax'
  result: OperandSyntax[] | null
}

export interface ReturnSyntax extends Span {
  _syntax: 'ReturnSyntax'
  result: OperandSyntax[] | null
}

export interface LoopSyntax extends Span {
  _syntax: 'LoopSyntax'
  name: string
}

export interface BreakSyntax extends Span {
  _syntax: 'BreakSyntax'
  name: LoopSyntax | null
  result: OperandSyntax[] | null
}

export interface ContinueSyntax extends Span {
  _syntax: 'ContinueSyntax'
  name: LoopSyntax | null
}

export interface TypeAnnotationSyntax extends Span {
  _syntax: 'TypeAnnotationSyntax'
  type: TypeSyntax
}

export interface PropertySyntax extends Span {
  _syntax: 'PropertySyntax'
  name: string
  annotation: TypeAnnotationSyntax
  initializer: InitializerSyntax | null
  attributes: AttributeSyntax[] | null
}

export interface FieldSyntax extends Span {
  _syntax: 'FieldSyntax'
  property: PropertySyntax
}

export type PartSyntax =
  | FieldSyntax
  | PropertySyntax

export interface StructureSyntax extends Span {
  _syntax: 'StructureSyntax'
  parts: PartSyntax[] | null
}

export interface ArraySyntax extends Span {
  _syntax: 'ArraySyntax'
  members: TypeSyntax[] | null
}

export type BindingSpecSyntax =
  | StructureSyntax
  | TypeSyntax
  | ArraySyntax

export interface BindingAnnotationSyntax extends Span {
  _syntax: 'BindingAnnotationSyntax'
  spec: BindingSpecSyntax
}

export interface BindingSyntax extends Span {
  _syntax: 'BindingSyntax'
  name: string
  annotation: BindingAnnotationSyntax | null
  operation: OperandSyntax[]
}

export interface MutableSyntax extends Span {
  _syntax: 'MutableSyntax'
  binding: BindingSyntax
}

export interface VarSyntax extends Span {
  _syntax: 'VarSyntax'
  binding: BindingSyntax
}

export interface LetSyntax extends Span {
  _syntax: 'LetSyntax'
  binding: BindingSyntax
}

export type CommandSyntax =
  | OperationSyntax
  | LetSyntax
  | VarSyntax
  | MutableSyntax
  | SetSyntax
  | ContinueSyntax
  | BreakSyntax
  | ReturnSyntax
  | ThrowSyntax

export interface WhenSyntax extends Span {
  _syntax: 'WhenSyntax'
  name: string
  variant: NameSyntax
  command: CommandSyntax
}

export type ConditionSyntax =
  | OperationSyntax
  | LetSyntax

export interface TrySyntax extends Span {
  _syntax: 'TrySyntax'
  condition: ConditionSyntax
  cases: WhenSyntax[] | null
  dropper: ElseSyntax | null
}

export interface ChooseSyntax extends Span {
  _syntax: 'ChooseSyntax'
  condition: OperandSyntax[]
  cases: WhenSyntax[] | null
  alternative: ElseSyntax | null
}

export interface WhileSyntax extends Span {
  _syntax: 'WhileSyntax'
  condition: ConditionSyntax
  name: LabelSyntax | null
  action: ActionSyntax
}

export interface StatementSyntax extends Span {
  _syntax: 'StatementSyntax'
  command: CommandSyntax
}

export interface CaseSyntax extends Span {
  _syntax: 'CaseSyntax'
  condition: OperandSyntax[]
}

export interface BranchSyntax extends Span {
  _syntax: 'BranchSyntax'
  cases: CaseSyntax[]
  consequent: StatementSyntax
}

export interface MatchSyntax extends Span {
  _syntax: 'MatchSyntax'
  scrutinee: OperandSyntax[]
  branches: BranchSyntax[]
  alternative: ElseSyntax | null
}

export interface ElseSyntax extends Span {
  _syntax: 'ElseSyntax'
  alternative: CommandSyntax
}

export interface IfSyntax extends Span {
  _syntax: 'IfSyntax'
  condition: OperandSyntax[]
  consequent: CommandSyntax
  alternative: ElseSyntax | null
}

export interface BlockSyntax extends Span {
  _syntax: 'BlockSyntax'
  uses: UseSyntax[] | null
  statements: StatementSyntax[] | null
}

export interface ElementSyntax extends Span {
  _syntax: 'ElementSyntax'
  operation: OperandSyntax[]
  attributes: AttributeSyntax[] | null
}

export interface VectorSyntax extends Span {
  _syntax: 'VectorSyntax'
  elements: ElementSyntax[]
  lifetime: LifetimeSyntax | null
}

export interface ValueSyntax extends Span {
  _syntax: 'ValueSyntax'
  value: OperandSyntax[]
  attributes: AttributeSyntax[] | null
}

export interface ComponentSyntax extends Span {
  _syntax: 'ComponentSyntax'
  operands: OperandSyntax[]
  attributes: AttributeSyntax[] | null
  value: ValueSyntax | null
}

export interface ObjectSyntax extends Span {
  _syntax: 'ObjectSyntax'
  components: ComponentSyntax[] | null
}

export interface LiteralSyntax extends Span {
  _syntax: 'LiteralSyntax'
  literal: Literal
}

export type ExpressionSyntax =
  | LiteralSyntax
  | TypeSyntax
  | ObjectSyntax
  | VectorSyntax
  | BlockSyntax
  | IfSyntax
  | MatchSyntax
  | LambdaSyntax
  | ForSyntax
  | WhileSyntax
  | ChooseSyntax
  | TrySyntax
  | RepeatSyntax
  | SizeOfSyntax
  | IsSyntax

export interface MemberAccessSyntax extends Span {
  _syntax: 'MemberAccessSyntax'
  name: NameSyntax
}

export interface OperandSyntax extends Span {
  _syntax: 'OperandSyntax'
  expression: ExpressionSyntax
  members: MemberAccessSyntax[] | null
}

export interface InitializerSyntax extends Span {
  _syntax: 'InitializerSyntax'
  operands: OperandSyntax[]
}

export interface PackageSyntax extends Span {
  _syntax: 'PackageSyntax'
  name: NameSyntax
}

export interface ModuleSyntax extends Span {
  _syntax: 'ModuleSyntax'
  name: string
}

export type ModelSyntax =
  | LiteralSyntax
  | NameSyntax
  | ObjectSyntax
  | VectorSyntax

export interface AttributeSyntax extends Span {
  _syntax: 'AttributeSyntax'
  name: string
  model: ModelSyntax
}

export interface MacroSyntax extends Span {
  _syntax: 'MacroSyntax'
  name: string
  model: ModelSyntax
  rule: OperandSyntax[]
}

export interface ExtendSyntax extends Span {
  _syntax: 'ExtendSyntax'
  type: TypeSyntax
}

export interface ExtendsSyntax extends Span {
  _syntax: 'ExtendsSyntax'
  extensions: ExtendSyntax[] | null
}

export interface IntrinsicSyntax extends Span {
  _syntax: 'IntrinsicSyntax'
}

export interface InstructionSyntax extends Span {
  _syntax: 'InstructionSyntax'
}

export interface ExternSyntax extends Span {
  _syntax: 'ExternSyntax'
}

export type ImplementationSyntax =
  | ActionSyntax
  | ExternSyntax
  | InstructionSyntax
  | IntrinsicSyntax

export interface RoutineSyntax extends Span {
  _syntax: 'RoutineSyntax'
  generics: GenericArgumentsSyntax | null
  lifetime: LifetimeSyntax | null
  parameters: ParameterSetSyntax | null
  attributes: AttributeSyntax[] | null
  returns_: ReturnsSyntax | null
  throws_: ThrowsSyntax | null
  implementation: ImplementationSyntax
}

export interface NamedSyntax extends Span {
  _syntax: 'NamedSyntax'
  name: string
  routine: RoutineSyntax
}

export type TargetSyntax =
  | NamedSyntax
  | RoutineSyntax

export interface OperatorSyntax extends Span {
  _syntax: 'OperatorSyntax'
  target: TargetSyntax
}

export interface ProcedureSyntax extends Span {
  _syntax: 'ProcedureSyntax'
  target: TargetSyntax
}

export interface FunctionSyntax extends Span {
  _syntax: 'FunctionSyntax'
  target: TargetSyntax
}

export interface DeInitSyntax extends Span {
  _syntax: 'DeInitSyntax'
  action: ActionSyntax
}

export interface InitSyntax extends Span {
  _syntax: 'InitSyntax'
  parameters: ParameterSetSyntax | null
  action: ActionSyntax
}

export type MethodSyntax =
  | FunctionSyntax
  | ProcedureSyntax
  | OperatorSyntax

export interface TraitSyntax extends Span {
  _syntax: 'TraitSyntax'
  name: NameSyntax
  extension: ExtendsSyntax | null
  attributes: AttributeSyntax[] | null
  uses: UseSyntax[] | null
  functions: MethodSyntax[] | null
}

export interface ImplementSyntax extends Span {
  _syntax: 'ImplementSyntax'
  type: TypeSyntax
  attributes: AttributeSyntax[] | null
  uses: UseSyntax[] | null
  methods: MethodSyntax[] | null
}

export interface UseSyntax extends Span {
  _syntax: 'UseSyntax'
  name: NameSyntax
}

export interface ThrowsSyntax extends Span {
  _syntax: 'ThrowsSyntax'
  type: TypeSyntax
  attributes: AttributeSyntax[] | null
}

export interface ReturnsSyntax extends Span {
  _syntax: 'ReturnsSyntax'
  type: TypeSyntax
  attributes: AttributeSyntax[] | null
}

export interface ItemSyntax extends Span {
  _syntax: 'ItemSyntax'
  name: string
  annotation: TypeAnnotationSyntax | null
  attributes: AttributeSyntax[] | null
}

export interface ParametersSyntax extends Span {
  _syntax: 'ParametersSyntax'
  items: ItemSyntax[] | null
}

export type ParameterSetSyntax =
  | ParametersSyntax
  | TypeSyntax

export interface OptionalSyntax extends Span {
  _syntax: 'OptionalSyntax'
}

export interface GenericArgumentSyntax extends Span {
  _syntax: 'GenericArgumentSyntax'
  type: TypeSyntax
}

export interface GenericArgumentsSyntax extends Span {
  _syntax: 'GenericArgumentsSyntax'
  generics: GenericArgumentSyntax[] | null
}

export interface DelegateSyntax extends Span {
  _syntax: 'DelegateSyntax'
  parameters: ParameterSetSyntax | null
  attributes: AttributeSyntax[] | null
  result: ReturnsSyntax | null
  error: ThrowsSyntax | null
}

export interface ConstantSyntax extends Span {
  _syntax: 'ConstantSyntax'
  type: TypeSyntax
  operation: OperandSyntax[] | null
}

export interface VariantSyntax extends Span {
  _syntax: 'VariantSyntax'
  name: string
  attributes: AttributeSyntax[] | null
  annotation: TypeAnnotationSyntax | null
}

export interface UnionSyntax extends Span {
  _syntax: 'UnionSyntax'
  variants: VariantSyntax[]
  body: BodySyntax | null
}

export interface NamespaceSyntax extends Span {
  _syntax: 'NamespaceSyntax'
  uses: UseSyntax[] | null
  declarations: DeclarationSyntax[] | null
}

export interface BodySyntax extends Span {
  _syntax: 'BodySyntax'
  uses: UseSyntax[] | null
  inits: InitSyntax[] | null
  deInit: DeInitSyntax | null
  members: MemberSyntax[] | null
}

export interface ClassSyntax extends Span {
  _syntax: 'ClassSyntax'
  structure: StructureSyntax
  body: BodySyntax | null
}

export type ConceptSyntax =
  | ClassSyntax
  | NamespaceSyntax
  | UnionSyntax
  | ConstantSyntax
  | DelegateSyntax
  | IntrinsicSyntax

export interface GenericParameterSyntax extends Span {
  _syntax: 'GenericParameterSyntax'
  name: string
  attributes: AttributeSyntax[] | null
}

export interface GenericParametersSyntax extends Span {
  _syntax: 'GenericParametersSyntax'
  parameters: GenericParameterSyntax[]
}

export interface DefinitionSyntax extends Span {
  _syntax: 'DefinitionSyntax'
  name: string
  parameters: GenericParametersSyntax | null
  attributes: AttributeSyntax[] | null
  concept_: ConceptSyntax
}

export type ConstituentSyntax =
  | DefinitionSyntax
  | FunctionSyntax
  | ProcedureSyntax
  | OperatorSyntax
  | ImplementSyntax
  | TraitSyntax
  | MacroSyntax
  | ModuleSyntax

export interface MemberSyntax extends Span {
  _syntax: 'MemberSyntax'
  constituent: ConstituentSyntax
}

export type ExportSyntax =
  | DefinitionSyntax
  | FunctionSyntax
  | OperatorSyntax
  | TraitSyntax
  | ModuleSyntax

export interface PrivateSyntax extends Span {
  _syntax: 'PrivateSyntax'
  export_: ExportSyntax
}

export type SymbolSyntax =
  | PrivateSyntax
  | DefinitionSyntax
  | FunctionSyntax
  | OperatorSyntax
  | TraitSyntax
  | MacroSyntax
  | ModuleSyntax

export interface DeclarationSyntax extends Span {
  _syntax: 'DeclarationSyntax'
  symbol: SymbolSyntax
}

export interface FileSyntax extends Span {
  _syntax: 'FileSyntax'
  packages: PackageSyntax[] | null
  uses: UseSyntax[] | null
  declarations: DeclarationSyntax[] | null
}

export interface ProgramSyntax extends Span {
  _syntax: 'ProgramSyntax'
  file: FileSyntax
  statements: StatementSyntax[] | null
}
