// SyntaxDump.h - Generated from scaly.sgm
// DO NOT EDIT - generated by codegen
// JSON serialization for AST inspection

#pragma once

#include "Syntax.h"
#include "llvm/Support/raw_ostream.h"
#include <string>

namespace scaly {

class SyntaxDumper {
    llvm::raw_ostream &OS;
    int Indent = 0;

    void indent() { for (int i = 0; i < Indent; i++) OS << "  "; }
    void nl() { OS << "\n"; }

    void key(const char *k) { indent(); OS << "\"" << k << "\": "; }
    void strVal(llvm::StringRef s) {
        OS << "\"";
        for (char c : s) {
            if (c == '"') OS << "\\\"";
            else if (c == '\\') OS << "\\\\";
            else if (c == '\n') OS << "\\n";
            else if (c == '\r') OS << "\\r";
            else if (c == '\t') OS << "\\t";
            else OS << c;
        }
        OS << "\"";
    }

public:
    SyntaxDumper(llvm::raw_ostream &os) : OS(os) {}

    void dumpSpan(size_t Start, size_t End) {
        key("start"); OS << Start << ","; nl();
        key("end"); OS << End;
    }

    void dump(const ThrownSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Thrown\","; nl();
        dumpSpan(N.Start, N.End);
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const ReferenceSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Reference\","; nl();
        dumpSpan(N.Start, N.End);
        OS << ","; nl();
        key("location"); strVal(N.location);
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const LocalSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Local\","; nl();
        dumpSpan(N.Start, N.End);
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const CallSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Call\","; nl();
        dumpSpan(N.Start, N.End);
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const LifetimeSyntax &N) {
        std::visit([this](const auto &V) { dump(V); }, N.Value);
    }
    void dump(const ExtensionSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Extension\","; nl();
        dumpSpan(N.Start, N.End);
        OS << ","; nl();
        key("name"); strVal(N.name);
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const NameSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Name\","; nl();
        dumpSpan(N.Start, N.End);
        OS << ","; nl();
        key("name"); strVal(N.name);
        if (N.extensions) {
            OS << ","; nl();
            key("extensions"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.extensions->size(); i++) {
                indent(); dump((*N.extensions)[i]);
                if (i + 1 < N.extensions->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const TypeSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Type\","; nl();
        dumpSpan(N.Start, N.End);
        OS << ","; nl();
        key("name"); dump(N.name);
        if (N.generics) {
            OS << ","; nl();
            key("generics"); dump(*N.generics);
        }
        if (N.optional) {
            OS << ","; nl();
            key("optional"); dump(*N.optional);
        }
        if (N.lifetime) {
            OS << ","; nl();
            key("lifetime"); dump(*N.lifetime);
        }
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const AsSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"As\","; nl();
        dumpSpan(N.Start, N.End);
        OS << ","; nl();
        key("type"); dump(N.type);
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const IsSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Is\","; nl();
        dumpSpan(N.Start, N.End);
        OS << ","; nl();
        key("name"); dump(N.name);
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const AlignOfSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"AlignOf\","; nl();
        dumpSpan(N.Start, N.End);
        OS << ","; nl();
        key("type"); dump(N.type);
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const SizeOfSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"SizeOf\","; nl();
        dumpSpan(N.Start, N.End);
        OS << ","; nl();
        key("type"); dump(N.type);
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const BlockSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Block\","; nl();
        dumpSpan(N.Start, N.End);
        if (N.uses) {
            OS << ","; nl();
            key("uses"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.uses->size(); i++) {
                indent(); dump((*N.uses)[i]);
                if (i + 1 < N.uses->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        if (N.statements) {
            OS << ","; nl();
            key("statements"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.statements->size(); i++) {
                indent(); dump((*N.statements)[i]);
                if (i + 1 < N.statements->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const SetSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Set\","; nl();
        dumpSpan(N.Start, N.End);
        if (N.target) {
            OS << ","; nl();
            key("target"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.target->size(); i++) {
                indent(); dump((*N.target)[i]);
                if (i + 1 < N.target->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        if (N.source) {
            OS << ","; nl();
            key("source"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.source->size(); i++) {
                indent(); dump((*N.source)[i]);
                if (i + 1 < N.source->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const OperationSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Operation\","; nl();
        dumpSpan(N.Start, N.End);
        if (N.operands) {
            OS << ","; nl();
            key("operands"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.operands->size(); i++) {
                indent(); dump((*N.operands)[i]);
                if (i + 1 < N.operands->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const ActionSyntax &N) {
        std::visit([this](const auto &V) { dump(V); }, N.Value);
    }
    void dump(const RepeatSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Repeat\","; nl();
        dumpSpan(N.Start, N.End);
        if (N.name) {
            OS << ","; nl();
            key("name"); dump(*N.name);
        }
        OS << ","; nl();
        key("action"); dump(N.action);
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const LabelSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Label\","; nl();
        dumpSpan(N.Start, N.End);
        OS << ","; nl();
        key("name"); strVal(N.name);
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const ForSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"For\","; nl();
        dumpSpan(N.Start, N.End);
        OS << ","; nl();
        key("variable"); strVal(N.variable);
        if (N.annotation) {
            OS << ","; nl();
            key("annotation"); dump(*N.annotation);
        }
        if (N.operation) {
            OS << ","; nl();
            key("operation"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.operation->size(); i++) {
                indent(); dump((*N.operation)[i]);
                if (i + 1 < N.operation->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        if (N.name) {
            OS << ","; nl();
            key("name"); dump(*N.name);
        }
        OS << ","; nl();
        key("action"); dump(N.action);
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const LambdaSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Lambda\","; nl();
        dumpSpan(N.Start, N.End);
        if (N.input) {
            OS << ","; nl();
            key("input"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.input->size(); i++) {
                indent(); dump((*N.input)[i]);
                if (i + 1 < N.input->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        OS << ","; nl();
        key("block"); dump(N.block);
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const ThrowSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Throw\","; nl();
        dumpSpan(N.Start, N.End);
        if (N.result) {
            OS << ","; nl();
            key("result"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.result->size(); i++) {
                indent(); dump((*N.result)[i]);
                if (i + 1 < N.result->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const ReturnSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Return\","; nl();
        dumpSpan(N.Start, N.End);
        if (N.result) {
            OS << ","; nl();
            key("result"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.result->size(); i++) {
                indent(); dump((*N.result)[i]);
                if (i + 1 < N.result->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const LoopSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Loop\","; nl();
        dumpSpan(N.Start, N.End);
        OS << ","; nl();
        key("name"); strVal(N.name);
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const BreakSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Break\","; nl();
        dumpSpan(N.Start, N.End);
        if (N.name) {
            OS << ","; nl();
            key("name"); dump(*N.name);
        }
        if (N.result) {
            OS << ","; nl();
            key("result"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.result->size(); i++) {
                indent(); dump((*N.result)[i]);
                if (i + 1 < N.result->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const ContinueSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Continue\","; nl();
        dumpSpan(N.Start, N.End);
        if (N.name) {
            OS << ","; nl();
            key("name"); dump(*N.name);
        }
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const TypeAnnotationSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"TypeAnnotation\","; nl();
        dumpSpan(N.Start, N.End);
        OS << ","; nl();
        key("type"); dump(N.type);
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const PropertySyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Property\","; nl();
        dumpSpan(N.Start, N.End);
        OS << ","; nl();
        key("name"); strVal(N.name);
        OS << ","; nl();
        key("annotation"); dump(N.annotation);
        if (N.initializer) {
            OS << ","; nl();
            key("initializer"); dump(*N.initializer);
        }
        if (N.attributes) {
            OS << ","; nl();
            key("attributes"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.attributes->size(); i++) {
                indent(); dump((*N.attributes)[i]);
                if (i + 1 < N.attributes->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const FieldSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Field\","; nl();
        dumpSpan(N.Start, N.End);
        OS << ","; nl();
        key("property"); dump(N.property);
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const PartSyntax &N) {
        std::visit([this](const auto &V) { dump(V); }, N.Value);
    }
    void dump(const StructureSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Structure\","; nl();
        dumpSpan(N.Start, N.End);
        if (N.parts) {
            OS << ","; nl();
            key("parts"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.parts->size(); i++) {
                indent(); dump((*N.parts)[i]);
                if (i + 1 < N.parts->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const ArraySyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Array\","; nl();
        dumpSpan(N.Start, N.End);
        if (N.members) {
            OS << ","; nl();
            key("members"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.members->size(); i++) {
                indent(); dump((*N.members)[i]);
                if (i + 1 < N.members->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const BindingSpecSyntax &N) {
        std::visit([this](const auto &V) { dump(V); }, N.Value);
    }
    void dump(const BindingAnnotationSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"BindingAnnotation\","; nl();
        dumpSpan(N.Start, N.End);
        OS << ","; nl();
        key("spec"); dump(N.spec);
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const BindingSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Binding\","; nl();
        dumpSpan(N.Start, N.End);
        OS << ","; nl();
        key("name"); strVal(N.name);
        if (N.annotation) {
            OS << ","; nl();
            key("annotation"); dump(*N.annotation);
        }
        if (N.operation) {
            OS << ","; nl();
            key("operation"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.operation->size(); i++) {
                indent(); dump((*N.operation)[i]);
                if (i + 1 < N.operation->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const MutableSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Mutable\","; nl();
        dumpSpan(N.Start, N.End);
        OS << ","; nl();
        key("binding"); dump(N.binding);
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const VarSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Var\","; nl();
        dumpSpan(N.Start, N.End);
        OS << ","; nl();
        key("binding"); dump(N.binding);
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const LetSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Let\","; nl();
        dumpSpan(N.Start, N.End);
        OS << ","; nl();
        key("binding"); dump(N.binding);
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const CommandSyntax &N) {
        std::visit([this](const auto &V) { dump(V); }, N.Value);
    }
    void dump(const WhenSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"When\","; nl();
        dumpSpan(N.Start, N.End);
        OS << ","; nl();
        key("name"); strVal(N.name);
        OS << ","; nl();
        key("variant"); dump(N.variant);
        OS << ","; nl();
        key("command"); dump(N.command);
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const ConditionSyntax &N) {
        std::visit([this](const auto &V) { dump(V); }, N.Value);
    }
    void dump(const TrySyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Try\","; nl();
        dumpSpan(N.Start, N.End);
        OS << ","; nl();
        key("condition"); dump(N.condition);
        if (N.cases) {
            OS << ","; nl();
            key("cases"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.cases->size(); i++) {
                indent(); dump((*N.cases)[i]);
                if (i + 1 < N.cases->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        if (N.dropper) {
            OS << ","; nl();
            key("dropper"); dump(*N.dropper);
        }
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const ChooseSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Choose\","; nl();
        dumpSpan(N.Start, N.End);
        if (N.condition) {
            OS << ","; nl();
            key("condition"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.condition->size(); i++) {
                indent(); dump((*N.condition)[i]);
                if (i + 1 < N.condition->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        if (N.cases) {
            OS << ","; nl();
            key("cases"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.cases->size(); i++) {
                indent(); dump((*N.cases)[i]);
                if (i + 1 < N.cases->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        if (N.alternative) {
            OS << ","; nl();
            key("alternative"); dump(*N.alternative);
        }
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const WhileSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"While\","; nl();
        dumpSpan(N.Start, N.End);
        OS << ","; nl();
        key("condition"); dump(N.condition);
        if (N.name) {
            OS << ","; nl();
            key("name"); dump(*N.name);
        }
        OS << ","; nl();
        key("action"); dump(N.action);
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const StatementSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Statement\","; nl();
        dumpSpan(N.Start, N.End);
        OS << ","; nl();
        key("command"); dump(N.command);
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const CaseSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Case\","; nl();
        dumpSpan(N.Start, N.End);
        if (N.condition) {
            OS << ","; nl();
            key("condition"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.condition->size(); i++) {
                indent(); dump((*N.condition)[i]);
                if (i + 1 < N.condition->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const BranchSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Branch\","; nl();
        dumpSpan(N.Start, N.End);
        if (N.cases) {
            OS << ","; nl();
            key("cases"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.cases->size(); i++) {
                indent(); dump((*N.cases)[i]);
                if (i + 1 < N.cases->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        OS << ","; nl();
        key("consequent"); dump(N.consequent);
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const MatchSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Match\","; nl();
        dumpSpan(N.Start, N.End);
        if (N.scrutinee) {
            OS << ","; nl();
            key("scrutinee"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.scrutinee->size(); i++) {
                indent(); dump((*N.scrutinee)[i]);
                if (i + 1 < N.scrutinee->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        if (N.branches) {
            OS << ","; nl();
            key("branches"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.branches->size(); i++) {
                indent(); dump((*N.branches)[i]);
                if (i + 1 < N.branches->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        if (N.alternative) {
            OS << ","; nl();
            key("alternative"); dump(*N.alternative);
        }
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const ElseSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Else\","; nl();
        dumpSpan(N.Start, N.End);
        OS << ","; nl();
        key("alternative"); dump(N.alternative);
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const ThenSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Then\","; nl();
        dumpSpan(N.Start, N.End);
        OS << ","; nl();
        key("command"); dump(N.command);
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const IfSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"If\","; nl();
        dumpSpan(N.Start, N.End);
        if (N.condition) {
            OS << ","; nl();
            key("condition"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.condition->size(); i++) {
                indent(); dump((*N.condition)[i]);
                if (i + 1 < N.condition->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        OS << ","; nl();
        key("consequent"); dump(N.consequent);
        OS << ","; nl();
        key("alternative"); dump(N.alternative);
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const ElementSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Element\","; nl();
        dumpSpan(N.Start, N.End);
        if (N.operation) {
            OS << ","; nl();
            key("operation"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.operation->size(); i++) {
                indent(); dump((*N.operation)[i]);
                if (i + 1 < N.operation->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        if (N.attributes) {
            OS << ","; nl();
            key("attributes"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.attributes->size(); i++) {
                indent(); dump((*N.attributes)[i]);
                if (i + 1 < N.attributes->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const VectorSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Vector\","; nl();
        dumpSpan(N.Start, N.End);
        if (N.elements) {
            OS << ","; nl();
            key("elements"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.elements->size(); i++) {
                indent(); dump((*N.elements)[i]);
                if (i + 1 < N.elements->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        if (N.lifetime) {
            OS << ","; nl();
            key("lifetime"); dump(*N.lifetime);
        }
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const ValueSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Value\","; nl();
        dumpSpan(N.Start, N.End);
        if (N.value) {
            OS << ","; nl();
            key("value"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.value->size(); i++) {
                indent(); dump((*N.value)[i]);
                if (i + 1 < N.value->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        if (N.attributes) {
            OS << ","; nl();
            key("attributes"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.attributes->size(); i++) {
                indent(); dump((*N.attributes)[i]);
                if (i + 1 < N.attributes->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const ComponentSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Component\","; nl();
        dumpSpan(N.Start, N.End);
        if (N.operands) {
            OS << ","; nl();
            key("operands"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.operands->size(); i++) {
                indent(); dump((*N.operands)[i]);
                if (i + 1 < N.operands->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        if (N.attributes) {
            OS << ","; nl();
            key("attributes"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.attributes->size(); i++) {
                indent(); dump((*N.attributes)[i]);
                if (i + 1 < N.attributes->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        if (N.value) {
            OS << ","; nl();
            key("value"); dump(*N.value);
        }
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const ObjectSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Object\","; nl();
        dumpSpan(N.Start, N.End);
        if (N.components) {
            OS << ","; nl();
            key("components"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.components->size(); i++) {
                indent(); dump((*N.components)[i]);
                if (i + 1 < N.components->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const LiteralSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Literal\","; nl();
        dumpSpan(N.Start, N.End);
        OS << ","; nl();
        key("literal"); dumpLiteral(N.literal);
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const ExpressionSyntax &N) {
        std::visit([this](const auto &V) { dump(V); }, N.Value);
    }
    void dump(const MemberAccessSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"MemberAccess\","; nl();
        dumpSpan(N.Start, N.End);
        OS << ","; nl();
        key("name"); dump(N.name);
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const OperandSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Operand\","; nl();
        dumpSpan(N.Start, N.End);
        OS << ","; nl();
        key("expression"); dump(N.expression);
        if (N.members) {
            OS << ","; nl();
            key("members"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.members->size(); i++) {
                indent(); dump((*N.members)[i]);
                if (i + 1 < N.members->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const InitializerSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Initializer\","; nl();
        dumpSpan(N.Start, N.End);
        if (N.operands) {
            OS << ","; nl();
            key("operands"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.operands->size(); i++) {
                indent(); dump((*N.operands)[i]);
                if (i + 1 < N.operands->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const VersionSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Version\","; nl();
        dumpSpan(N.Start, N.End);
        OS << ","; nl();
        key("majorMinor"); dumpLiteral(N.majorMinor);
        OS << ","; nl();
        key("patch"); dumpLiteral(N.patch);
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const PackageSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Package\","; nl();
        dumpSpan(N.Start, N.End);
        OS << ","; nl();
        key("name"); dump(N.name);
        if (N.version) {
            OS << ","; nl();
            key("version"); dump(*N.version);
        }
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const ModuleSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Module\","; nl();
        dumpSpan(N.Start, N.End);
        OS << ","; nl();
        key("name"); strVal(N.name);
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const ModelSyntax &N) {
        std::visit([this](const auto &V) { dump(V); }, N.Value);
    }
    void dump(const AttributeSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Attribute\","; nl();
        dumpSpan(N.Start, N.End);
        OS << ","; nl();
        key("name"); strVal(N.name);
        OS << ","; nl();
        key("model"); dump(N.model);
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const MacroSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Macro\","; nl();
        dumpSpan(N.Start, N.End);
        OS << ","; nl();
        key("name"); strVal(N.name);
        OS << ","; nl();
        key("model"); dump(N.model);
        if (N.rule) {
            OS << ","; nl();
            key("rule"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.rule->size(); i++) {
                indent(); dump((*N.rule)[i]);
                if (i + 1 < N.rule->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const ExtendSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Extend\","; nl();
        dumpSpan(N.Start, N.End);
        OS << ","; nl();
        key("type"); dump(N.type);
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const ExtendsSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Extends\","; nl();
        dumpSpan(N.Start, N.End);
        if (N.extensions) {
            OS << ","; nl();
            key("extensions"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.extensions->size(); i++) {
                indent(); dump((*N.extensions)[i]);
                if (i + 1 < N.extensions->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const IntrinsicSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Intrinsic\","; nl();
        dumpSpan(N.Start, N.End);
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const InstructionSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Instruction\","; nl();
        dumpSpan(N.Start, N.End);
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const ExternSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Extern\","; nl();
        dumpSpan(N.Start, N.End);
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const ImplementationSyntax &N) {
        std::visit([this](const auto &V) { dump(V); }, N.Value);
    }
    void dump(const RoutineSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Routine\","; nl();
        dumpSpan(N.Start, N.End);
        if (N.generics) {
            OS << ","; nl();
            key("generics"); dump(*N.generics);
        }
        if (N.lifetime) {
            OS << ","; nl();
            key("lifetime"); dump(*N.lifetime);
        }
        if (N.parameters) {
            OS << ","; nl();
            key("parameters"); dump(*N.parameters);
        }
        if (N.attributes) {
            OS << ","; nl();
            key("attributes"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.attributes->size(); i++) {
                indent(); dump((*N.attributes)[i]);
                if (i + 1 < N.attributes->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        if (N.returns_) {
            OS << ","; nl();
            key("returns_"); dump(*N.returns_);
        }
        if (N.throws_) {
            OS << ","; nl();
            key("throws_"); dump(*N.throws_);
        }
        OS << ","; nl();
        key("implementation"); dump(N.implementation);
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const NamedSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Named\","; nl();
        dumpSpan(N.Start, N.End);
        OS << ","; nl();
        key("name"); strVal(N.name);
        OS << ","; nl();
        key("routine"); dump(N.routine);
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const TargetSyntax &N) {
        std::visit([this](const auto &V) { dump(V); }, N.Value);
    }
    void dump(const OperatorSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Operator\","; nl();
        dumpSpan(N.Start, N.End);
        OS << ","; nl();
        key("target"); dump(N.target);
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const ProcedureSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Procedure\","; nl();
        dumpSpan(N.Start, N.End);
        OS << ","; nl();
        key("target"); dump(N.target);
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const FunctionSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Function\","; nl();
        dumpSpan(N.Start, N.End);
        OS << ","; nl();
        key("target"); dump(N.target);
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const DeInitSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"DeInit\","; nl();
        dumpSpan(N.Start, N.End);
        OS << ","; nl();
        key("action"); dump(N.action);
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const InitSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Init\","; nl();
        dumpSpan(N.Start, N.End);
        if (N.lifetime) {
            OS << ","; nl();
            key("lifetime"); dump(*N.lifetime);
        }
        if (N.parameters) {
            OS << ","; nl();
            key("parameters"); dump(*N.parameters);
        }
        OS << ","; nl();
        key("action"); dump(N.action);
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const MethodSyntax &N) {
        std::visit([this](const auto &V) { dump(V); }, N.Value);
    }
    void dump(const TraitSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Trait\","; nl();
        dumpSpan(N.Start, N.End);
        OS << ","; nl();
        key("name"); dump(N.name);
        if (N.extension) {
            OS << ","; nl();
            key("extension"); dump(*N.extension);
        }
        if (N.attributes) {
            OS << ","; nl();
            key("attributes"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.attributes->size(); i++) {
                indent(); dump((*N.attributes)[i]);
                if (i + 1 < N.attributes->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        if (N.uses) {
            OS << ","; nl();
            key("uses"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.uses->size(); i++) {
                indent(); dump((*N.uses)[i]);
                if (i + 1 < N.uses->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        if (N.functions) {
            OS << ","; nl();
            key("functions"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.functions->size(); i++) {
                indent(); dump((*N.functions)[i]);
                if (i + 1 < N.functions->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const ImplementSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Implement\","; nl();
        dumpSpan(N.Start, N.End);
        OS << ","; nl();
        key("type"); dump(N.type);
        if (N.attributes) {
            OS << ","; nl();
            key("attributes"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.attributes->size(); i++) {
                indent(); dump((*N.attributes)[i]);
                if (i + 1 < N.attributes->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        if (N.uses) {
            OS << ","; nl();
            key("uses"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.uses->size(); i++) {
                indent(); dump((*N.uses)[i]);
                if (i + 1 < N.uses->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        if (N.methods) {
            OS << ","; nl();
            key("methods"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.methods->size(); i++) {
                indent(); dump((*N.methods)[i]);
                if (i + 1 < N.methods->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const UseSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Use\","; nl();
        dumpSpan(N.Start, N.End);
        OS << ","; nl();
        key("name"); dump(N.name);
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const ThrowsSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Throws\","; nl();
        dumpSpan(N.Start, N.End);
        OS << ","; nl();
        key("type"); dump(N.type);
        if (N.attributes) {
            OS << ","; nl();
            key("attributes"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.attributes->size(); i++) {
                indent(); dump((*N.attributes)[i]);
                if (i + 1 < N.attributes->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const ReturnsSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Returns\","; nl();
        dumpSpan(N.Start, N.End);
        OS << ","; nl();
        key("type"); dump(N.type);
        if (N.attributes) {
            OS << ","; nl();
            key("attributes"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.attributes->size(); i++) {
                indent(); dump((*N.attributes)[i]);
                if (i + 1 < N.attributes->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const ItemSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Item\","; nl();
        dumpSpan(N.Start, N.End);
        OS << ","; nl();
        key("name"); strVal(N.name);
        if (N.annotation) {
            OS << ","; nl();
            key("annotation"); dump(*N.annotation);
        }
        if (N.attributes) {
            OS << ","; nl();
            key("attributes"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.attributes->size(); i++) {
                indent(); dump((*N.attributes)[i]);
                if (i + 1 < N.attributes->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const ParametersSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Parameters\","; nl();
        dumpSpan(N.Start, N.End);
        if (N.items) {
            OS << ","; nl();
            key("items"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.items->size(); i++) {
                indent(); dump((*N.items)[i]);
                if (i + 1 < N.items->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const ParameterSetSyntax &N) {
        std::visit([this](const auto &V) { dump(V); }, N.Value);
    }
    void dump(const OptionalSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Optional\","; nl();
        dumpSpan(N.Start, N.End);
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const GenericArgumentSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"GenericArgument\","; nl();
        dumpSpan(N.Start, N.End);
        OS << ","; nl();
        key("type"); dump(N.type);
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const GenericArgumentsSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"GenericArguments\","; nl();
        dumpSpan(N.Start, N.End);
        if (N.generics) {
            OS << ","; nl();
            key("generics"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.generics->size(); i++) {
                indent(); dump((*N.generics)[i]);
                if (i + 1 < N.generics->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const DelegateSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Delegate\","; nl();
        dumpSpan(N.Start, N.End);
        if (N.parameters) {
            OS << ","; nl();
            key("parameters"); dump(*N.parameters);
        }
        if (N.attributes) {
            OS << ","; nl();
            key("attributes"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.attributes->size(); i++) {
                indent(); dump((*N.attributes)[i]);
                if (i + 1 < N.attributes->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        if (N.result) {
            OS << ","; nl();
            key("result"); dump(*N.result);
        }
        if (N.error) {
            OS << ","; nl();
            key("error"); dump(*N.error);
        }
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const ConstantSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Constant\","; nl();
        dumpSpan(N.Start, N.End);
        OS << ","; nl();
        key("type"); dump(N.type);
        if (N.operation) {
            OS << ","; nl();
            key("operation"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.operation->size(); i++) {
                indent(); dump((*N.operation)[i]);
                if (i + 1 < N.operation->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const VariantSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Variant\","; nl();
        dumpSpan(N.Start, N.End);
        OS << ","; nl();
        key("name"); strVal(N.name);
        if (N.attributes) {
            OS << ","; nl();
            key("attributes"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.attributes->size(); i++) {
                indent(); dump((*N.attributes)[i]);
                if (i + 1 < N.attributes->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        if (N.annotation) {
            OS << ","; nl();
            key("annotation"); dump(*N.annotation);
        }
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const UnionSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Union\","; nl();
        dumpSpan(N.Start, N.End);
        if (N.variants) {
            OS << ","; nl();
            key("variants"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.variants->size(); i++) {
                indent(); dump((*N.variants)[i]);
                if (i + 1 < N.variants->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        if (N.body) {
            OS << ","; nl();
            key("body"); dump(*N.body);
        }
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const NamespaceSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Namespace\","; nl();
        dumpSpan(N.Start, N.End);
        if (N.uses) {
            OS << ","; nl();
            key("uses"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.uses->size(); i++) {
                indent(); dump((*N.uses)[i]);
                if (i + 1 < N.uses->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        if (N.declarations) {
            OS << ","; nl();
            key("declarations"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.declarations->size(); i++) {
                indent(); dump((*N.declarations)[i]);
                if (i + 1 < N.declarations->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const BodySyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Body\","; nl();
        dumpSpan(N.Start, N.End);
        if (N.uses) {
            OS << ","; nl();
            key("uses"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.uses->size(); i++) {
                indent(); dump((*N.uses)[i]);
                if (i + 1 < N.uses->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        if (N.inits) {
            OS << ","; nl();
            key("inits"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.inits->size(); i++) {
                indent(); dump((*N.inits)[i]);
                if (i + 1 < N.inits->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        if (N.deInit) {
            OS << ","; nl();
            key("deInit"); dump(*N.deInit);
        }
        if (N.members) {
            OS << ","; nl();
            key("members"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.members->size(); i++) {
                indent(); dump((*N.members)[i]);
                if (i + 1 < N.members->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const ClassSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Class\","; nl();
        dumpSpan(N.Start, N.End);
        OS << ","; nl();
        key("structure"); dump(N.structure);
        if (N.body) {
            OS << ","; nl();
            key("body"); dump(*N.body);
        }
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const ConceptSyntax &N) {
        std::visit([this](const auto &V) { dump(V); }, N.Value);
    }
    void dump(const GenericParameterSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"GenericParameter\","; nl();
        dumpSpan(N.Start, N.End);
        OS << ","; nl();
        key("name"); strVal(N.name);
        if (N.attributes) {
            OS << ","; nl();
            key("attributes"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.attributes->size(); i++) {
                indent(); dump((*N.attributes)[i]);
                if (i + 1 < N.attributes->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const GenericParametersSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"GenericParameters\","; nl();
        dumpSpan(N.Start, N.End);
        if (N.parameters) {
            OS << ","; nl();
            key("parameters"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.parameters->size(); i++) {
                indent(); dump((*N.parameters)[i]);
                if (i + 1 < N.parameters->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const DefinitionSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Definition\","; nl();
        dumpSpan(N.Start, N.End);
        OS << ","; nl();
        key("name"); strVal(N.name);
        if (N.parameters) {
            OS << ","; nl();
            key("parameters"); dump(*N.parameters);
        }
        if (N.attributes) {
            OS << ","; nl();
            key("attributes"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.attributes->size(); i++) {
                indent(); dump((*N.attributes)[i]);
                if (i + 1 < N.attributes->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        OS << ","; nl();
        key("concept_"); dump(N.concept_);
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const ConstituentSyntax &N) {
        std::visit([this](const auto &V) { dump(V); }, N.Value);
    }
    void dump(const MemberSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Member\","; nl();
        dumpSpan(N.Start, N.End);
        OS << ","; nl();
        key("constituent"); dump(N.constituent);
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const ExportSyntax &N) {
        std::visit([this](const auto &V) { dump(V); }, N.Value);
    }
    void dump(const PrivateSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Private\","; nl();
        dumpSpan(N.Start, N.End);
        OS << ","; nl();
        key("export_"); dump(N.export_);
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const SymbolSyntax &N) {
        std::visit([this](const auto &V) { dump(V); }, N.Value);
    }
    void dump(const DeclarationSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Declaration\","; nl();
        dumpSpan(N.Start, N.End);
        OS << ","; nl();
        key("symbol"); dump(N.symbol);
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const FileSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"File\","; nl();
        dumpSpan(N.Start, N.End);
        if (N.packages) {
            OS << ","; nl();
            key("packages"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.packages->size(); i++) {
                indent(); dump((*N.packages)[i]);
                if (i + 1 < N.packages->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        if (N.uses) {
            OS << ","; nl();
            key("uses"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.uses->size(); i++) {
                indent(); dump((*N.uses)[i]);
                if (i + 1 < N.uses->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        if (N.declarations) {
            OS << ","; nl();
            key("declarations"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.declarations->size(); i++) {
                indent(); dump((*N.declarations)[i]);
                if (i + 1 < N.declarations->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        nl(); Indent--; indent(); OS << "}";
    }
    void dump(const ProgramSyntax &N) {
        OS << "{"; nl(); Indent++;
        key("node"); OS << "\"Program\","; nl();
        dumpSpan(N.Start, N.End);
        OS << ","; nl();
        key("file"); dump(N.file);
        if (N.statements) {
            OS << ","; nl();
            key("statements"); OS << "["; nl(); Indent++;
            for (size_t i = 0; i < N.statements->size(); i++) {
                indent(); dump((*N.statements)[i]);
                if (i + 1 < N.statements->size()) OS << ",";
                nl();
            }
            Indent--; indent(); OS << "]";
        }
        nl(); Indent--; indent(); OS << "}";
    }

    // Literal dumper
    void dumpLiteral(const Literal &L) {
        std::visit([this](const auto &V) {
            using T = std::decay_t<decltype(V)>;
            if constexpr (std::is_same_v<T, StringLiteral>) {
                OS << "{\"type\": \"string\", \"value\": "; strVal(V.Value); OS << "}";
            } else if constexpr (std::is_same_v<T, IntegerLiteral>) {
                OS << "{\"type\": \"integer\", \"value\": "; strVal(V.Value); OS << "}";
            } else if constexpr (std::is_same_v<T, FloatingPointLiteral>) {
                OS << "{\"type\": \"float\", \"value\": "; strVal(V.Value); OS << "}";
            } else if constexpr (std::is_same_v<T, BooleanLiteral>) {
                OS << "{\"type\": \"boolean\", \"value\": " << (V.Value ? "true" : "false") << "}";
            } else if constexpr (std::is_same_v<T, HexLiteral>) {
                OS << "{\"type\": \"hex\", \"value\": "; strVal(V.Value); OS << "}";
            } else if constexpr (std::is_same_v<T, CharacterLiteral>) {
                OS << "{\"type\": \"character\", \"value\": "; strVal(V.Value); OS << "}";
            } else if constexpr (std::is_same_v<T, FragmentLiteral>) {
                OS << "{\"type\": \"fragment\", \"value\": "; strVal(V.Value); OS << "}";
            }
        }, L);
    }

};

} // namespace scaly
