#!/usr/bin/env bash
set -x
/opt/homebrew/opt/llvm/bin/clang++ -fcolor-diagnostics -fansi-escape-codes -ferror-limit=5 \
    -g \
    scaly.cpp \
    scaly/memory.cpp \
    scaly/memory/Object.cpp \
    scaly/memory/PageNode.cpp \
    scaly/memory/PageList.cpp \
    scaly/memory/PageListIterator.cpp \
    scaly/memory/Page.cpp \
    scaly/memory/Region.cpp \
    scaly/containers.cpp \
    scaly/containers/Node.cpp \
    scaly/containers/ListIterator.cpp \
    scaly/containers/List.cpp \
    scaly/containers/Vector.cpp \
    scaly/containers/Array.cpp \
    scaly/containers/BuilderListIterator.cpp \
    scaly/containers/BuilderList.cpp \
    scaly/containers/hashing.cpp \
    scaly/containers/HashSetBuilder.cpp \
    scaly/containers/HashSet.cpp \
    scaly/containers/HashMapBuilder.cpp \
    scaly/containers/HashMap.cpp \
    scaly/containers/MultiMapBuilder.cpp \
    scaly/containers/MultiMap.cpp \
    scaly/containers/String.cpp \
    scaly/containers/StringIterator.cpp \
    scaly/containers/StringBuilder.cpp \
    scaly/io.cpp \
    scaly/io/Console.cpp \
    scaly/io/FileError.cpp \
    scaly/io/Directory.cpp \
    scaly/io/File.cpp \
    scaly/io/Path.cpp \
    scaly/compiler.cpp \
    scaly/compiler/Errors.cpp \
    scaly/compiler/Lexer.cpp \
    scaly/compiler/Parser.cpp \
    scaly/compiler/Model.cpp \
    scaly/compiler/Modeler.cpp \
    scaly/compiler/ModelError.cpp \
    scaly/compiler/TranspilerError.cpp \
    scaly/compiler/Transpiler.cpp \
    scaly/compiler/Generator.cpp \
    scaly/compiler/CompilerError.cpp \
    scaly/compiler/Driver.cpp \
    main.cpp \
    -o bin/scaly\
    `llvm-config --cxxflags --ldflags --system-libs --libs core`
