<![CDATA[
;; Generate scalyls/grammar.scaly from scaly.sgm
;;
;; The scalyls semantic-token highlighter needs to know which identifiers are
;; reserved keywords. Rather than hand-maintaining that list (it would drift as
;; the language grows), generate it from the grammar's <keyword> elements - the
;; same single source of truth the parser's keyword set is generated from. Add
;; a <keyword> to scaly.sgm and the highlighter picks it up on the next ./mkp.

(define (generate-highlight-scaly) ($
"; grammar.scaly - Generated from scaly.sgm
; DO NOT EDIT - generated by codegen (./mkp)
;
; Grammar-derived classification for the scalyls semantic-token highlighter.
; The keyword set comes straight from the grammar's <keyword> elements, so new
; keywords flow into syntax highlighting automatically as the language grows.

use scaly.containers.String

define grammar
{
    ; True when `word` is a reserved keyword (scaly.sgm <keyword> list).
    function is_keyword(word: String) returns bool
    {
"   (apply-to-selected-children "keyword" (lambda (keyword) ($
"        guard word.equals(\""(id keyword)"\")
            return true
"   )))
"        false
    }
}
"
))
]]>
