<![CDATA[
;; Generate Scaly Parser from scaly.sgm

;; Helper to generate the char-literal argument for a punctuation value.
;; Bare double-quoted literals fold to parse_punctuation's u8 parameter in
;; call-argument position; the grammar's backslash value is already "\\",
;; which is the correct Scaly escape as-is.
(define (punct-const-name value)
    ($ "\"" value "\""))

(define (generate-parser-scaly) ($
"; parser.scaly - Generated from scaly.sgm
; DO NOT EDIT - generated by codegen

use scalyc.compiler.lexer.*
use scalyc.compiler.Syntax.*

define parser
{
; Parser error types
define DifferentSyntax()
define InvalidSyntax(start: size_t, end: size_t, message: String)

define ParserError union (
    Different: DifferentSyntax
    Invalid: InvalidSyntax
)

; Syntax types are defined in Syntax.scaly and the Lexer in lexer.scaly; both are
; loaded as SIBLING modules by compiler.scaly, and the two `use` clauses above are
; what bring their names in here.
;
; This file must NOT declare `module lexer` itself, and it did until 2026-08-14.
; A module declared inside `define parser` resolves to compiler/parser/lexer.scaly
; (Modeler.handle_namespace# appends the namespace name), that file does not exist,
; and a missing module file is SILENT: build_referenced_module# substitutes an
; empty stub with no diagnostic and no counter. So the declaration was dead weight
; nobody could see, until the scalyls codeLens for module resolution reported it.

define Parser
(
    lexer: Lexer
    keywords_index: Vector[String]
    keywords: HashSet[String]
)
{
    init(text: String)
    {
        ; `^this` is LOAD-BEARING, not decorative: the ctor allocates the
        ; Lexer + keyword tables on Page.get(this), so the Parser instance
        ; MUST be page-resident. The residency scan (concept_needs_this_
        ; residency) fires only when the init body has a literal `^this`
        ; Type - this is the one that triggers it, letting the Parser drop
        ; its implicit `rp`/page param (which the body never used). Removing
        ; the `^this` re-introduces a stack-allocated Parser whose
        ; Page.get(this) reads a garbage page header (SIGBUS).
        lexer := Lexer^this(text)
        keywords_index := initialize_keywords_index()
        keywords := initialize_keywords()
    }

    function initialize_keywords_index(this: Parser) returns Vector[String]
    {
        var keywords_builder Array[String]()
"   (apply-to-selected-children "keyword" (lambda (keyword) ($
"        keywords_builder.add(\""(id keyword)"\")
"   )))
"        Vector[String](keywords_builder)
    }

    procedure initialize_keywords(mutable this: Parser) returns HashSet[String]
    {
        var hash_set_builder HashSetBuilder[String](keywords_index)
        HashSet[String](hash_set_builder)
    }

    procedure parse_literal_token(mutable this: Parser) returns Literal throws ParserError
    {
        choose lexer.token
            when empty: Empty
                lexer.advance()
            else {}

        choose lexer.token
            when literal: Literal
            {
                ; Deep-copy the String payload onto rp so the literal survives
                ; future lexer token allocations that might reuse the same
                ; memory. Lexer scan_* procedures allocate Strings without an
                ; explicit page - those allocations go on ephemeral pages that
                ; can be reclaimed and overwritten by later parse phases.
                var ret_deep: Literal
                choose literal.value
                    when il: IntegerLiteral
                        ret_deep := Literal.Integer(IntegerLiteral(String(il.value)))
                    when sl: StringLiteral
                        ret_deep := Literal.String(StringLiteral(String(sl.value)))
                    when cl: CharacterLiteral
                        ret_deep := Literal.Character(CharacterLiteral(String(cl.value)))
                    when fl: FragmentLiteral
                        ret_deep := Literal.Fragment(FragmentLiteral(String(fl.value)))
                    when fp: FloatingPointLiteral
                        ret_deep := Literal.FloatingPoint(FloatingPointLiteral(String(fp.value)))
                    when hl: HexLiteral
                        ret_deep := Literal.Hex(HexLiteral(String(hl.value)))
                    else
                        ret_deep := literal.value
                lexer.empty()
                return ret_deep
            }
            else
                throw ParserError.Different(DifferentSyntax())
    }
"
    (apply-to-selected-children "syntax" (lambda (syntax) ($
        (if (multiple? syntax) ($
"
    procedure parse_"(downcase-string (id syntax))"_list(mutable this: Parser) returns ref[Vector["(id syntax)"Syntax]]? throws ParserError
    {
        var acc List["(id syntax)"Syntax]()
        var parsing: bool true
        while parsing
        {
            choose parse_"(downcase-string (id syntax))"()
                when err: Error
                {
                    ; Different = no more items; stop the list (or rethrow if the
                    ; list is still empty, so the caller sees Different). Invalid =
                    ; an item committed then hit a real syntax error; propagate it
                    ; instead of silently truncating the list (e.g. a no-else if).
                    choose err
                        when i: Invalid
                            throw ParserError.Invalid(i)
                        when d: Different
                        {
                            if acc.head = null
                                throw err
                            parsing := false
                        }
                }
                when node: Success
                    acc.add(node)
        }
        Vector["(id syntax)"Syntax](acc)
    }
"       ) "")
"
    procedure parse_"(downcase-string (id syntax))"(mutable this: Parser) returns "(id syntax)"Syntax throws ParserError
    {
"       (if (abstract? syntax)
            ;; Abstract syntax - try each alternative
            ($
                (apply-to-children-of syntax (lambda (content) ($
"        choose parse_"(downcase-string (link content))"()
            when err: Error
            {
                choose err
                    when i: Invalid
                        throw ParserError.Invalid(i)
                    when d: Different {}
            }
            when node: Success
                return "(id syntax)"Syntax."(link content)"(node)
"
                )))
"        throw ParserError.Different(DifferentSyntax())
"
            )
            ;; Concrete syntax - parse each field
            ($
"        let start lexer.previous_position
"               (if (peek? syntax) ($
"        var snapshot lexer.save_state()
        lexer.parse_colon()
"               ) "")
                (apply-to-children-of syntax (lambda (content)
                    (case (type content)
                        (("syntax")
                            (if (property content)
                            (let ((prop (property content))
                                  (type-name (if (multiple? content)
                                                 ($ "ref[Vector[" (link content) "Syntax]]?")
                                                 ($ (link content) "Syntax"))))
                            (if (optional? content)
                                ($
"
        let " prop "_start lexer.position
        var " prop ": ref[" (if (multiple? content) ($ "Vector[" (link content) "Syntax]") ($ (link content) "Syntax")) "]? null
        choose parse_"(downcase-string (link content))(if (multiple? content) "_list" "")"()
            when err: Error
            {
                choose err
                    when d: Different {}
                    when i: Invalid"
                                    (if (and (not (multiple? content)) (colon-opened? content))
" {}"
"
                        throw ParserError.Invalid(i)")
"
            }
            when success: Success
                " prop " := "
                                    (if (multiple? content)
                                        "success"
                                        (let ((target (element-with-id (link content))))
                                            (if (abstract? target)
                                                ($ (link content) "Syntax(success)")
                                                ($ (link content) "Syntax(success.start, success.end"
                                                   (apply-to-nodelist (properties target)
                                                       (lambda (p) ($ ", success." (property p))))
                                                   ")"))))
"
"
                                )
                                ;; non-optional syntax
                                ($
"
        let " prop "_start lexer.position
        var " prop ": " type-name "
        choose parse_"(downcase-string (link content))(if (multiple? content) "_list" "")"()
            when err: Error
"
                                    (if (equal? 1 (child-number content))
                                        "                throw err
"
                                        ($
"            {
                choose err
                    when d: Different
                        throw ParserError.Invalid(InvalidSyntax(" prop "_start, lexer.position, \"expected "(link content)"\"))
                    when i: Invalid
                        throw ParserError.Invalid(i)
            }
"
                                        )
                                    )
"            when success: Success
                " prop " := success
"
                                )
                            )) "")  ; close (if optional), (let), else "", close (if property)
                        )
                        (("literal")
                            (let ((prop (property content)))
                            ($
"
        var " prop ": Literal
        choose parse_literal_token()
            when err: Error
                throw err
            when success: Success
                " prop " := success
"
                            ))
                        )
                        (("keyword")
                            ($
"
        if ~lexer.parse_keyword(\""(id (element-with-id (link content)))"\")"
                                (if (equal? 1 (child-number content))
                                    (if (peek? syntax)
                                        "
        {
            lexer.restore_state(snapshot)
            throw ParserError.Different(DifferentSyntax())
        }
"
                                        "
            throw ParserError.Different(DifferentSyntax())
")
                                    ($ "
            throw ParserError.Invalid(InvalidSyntax(lexer.previous_position, lexer.position, \"expected '"(id (element-with-id (link content)))"'\"))
")
                                )
                            )
                        )
                        (("punctuation")
                            (if (optional? content)
                                ;; Optional punctuation - just try it
                                ($
"
        lexer.parse_punctuation("(punct-const-name (value (element-with-id (link content))))")
"                               )
                                ;; Required punctuation
                                ($
"
        if ~lexer.parse_punctuation("(punct-const-name (value (element-with-id (link content))))")"
                                    (if (equal? 1 (child-number content))
                                        "
            throw ParserError.Different(DifferentSyntax())
"
                                        ($ "
            throw ParserError.Invalid(InvalidSyntax(lexer.previous_position, lexer.position, \"expected '"(value (element-with-id (link content)))"'\"))
")
                                    )
                                )
                            )
                        )
                        (("colon")
                            (if (optional? content)
                                ;; Optional colon - just try it
                                ($
"
        lexer.parse_colon()
"                               )
                                ;; Required colon
                                ($
"
        if ~lexer.parse_colon()"
                                    (if (equal? 1 (child-number content))
                                        "
            throw ParserError.Different(DifferentSyntax())
"
                                        "
            throw ParserError.Invalid(InvalidSyntax(lexer.previous_position, lexer.position, \"expected colon or newline\"))
")
                                )
                            )
                        )
                        (("identifier")
                            (let ((prop (property content))
                                  (lead (node-list-first (select-elements (children (parent content)) "content"))))
                            ($
"
        let " prop " lexer.parse_identifier(keywords)
        if " prop ".length() = 0"
                                (cond
                                    ((equal? 1 (child-number content))
                                    "
            throw ParserError.Different(DifferentSyntax())
")
                                    ;; the identifier after ONE leading optional link (`Item`'s
                                    ;; `mutable`): nothing of this syntax was seen unless the
                                    ;; link was, so a missing name is DIFFERENT then, as it is
                                    ;; for a leading identifier
                                    ((and (equal? 2 (child-number content)) (optional? lead))
                                    ($ "
        {
            if " (property lead) " = null
                throw ParserError.Different(DifferentSyntax())
            throw ParserError.Invalid(InvalidSyntax(start, lexer.position, \"expected identifier\"))
        }
"))
                                    (else
                                    "
            throw ParserError.Invalid(InvalidSyntax(start, lexer.position, \"expected identifier\"))
"))
                            ))
                        )
                        (("attribute")
                            (let ((prop (property content)))
                            ($
"
        let " prop " lexer.parse_attribute()
        if " prop ".length() = 0"
                                (if (equal? 1 (child-number content))
                                    "
            throw ParserError.Different(DifferentSyntax())
"
                                    "
            throw ParserError.Invalid(InvalidSyntax(start, lexer.position, \"expected attribute\"))
")
                            ))
                        )
                        (else "")
                    )
                ))
                ;; End-of-input backstop, Program only: leftover tokens mean an
                ;; earlier construct silently truncated (its parse error was
                ;; swallowed by an optional-field/list path). Fail LOUDLY here
                ;; instead of dropping the rest of the program.
                (if (string=? "Program" (id syntax))
"
        var skipping_separators true
        while skipping_separators
            skipping_separators := lexer.parse_colon()
        var trailing_ok lexer.is_at_end()
        choose lexer.token
            when e: Empty {}
            else
                trailing_ok := false
        if trailing_ok = false
            throw ParserError.Invalid(InvalidSyntax(lexer.previous_position, lexer.position, \"unexpected trailing input - the construct before this point did not parse\"))
"
                    "")
"
        let end lexer.position

        "(id syntax)"Syntax(start, end"
                (apply-to-property-children-of syntax (lambda (content) ($
                    ", "
                    (if (or (equal? (type content) "keyword") (equal? (type content) "punctuation"))
                        "true"
                        (if (and (equal? (type content) "syntax") (not (multiple? content)) (not (optional? content)) (is-recursive-ref? syntax content))
                            ($ (link content)"Syntax("(property content)")")
                            (property content)))
                )))
                ")
"
            )
        )
"    }
"   )))
"
    function is_at_end(this: Parser) returns bool
        lexer.is_at_end()
}

function test() returns int
{
    ; Test 1: Parse a simple literal
    var parser Parser(\"42\")
    choose parser.parse_literal()
        when err: Error
            return 1
        when literal: Success
        {
            if ~parser.is_at_end()
                return 2
        }

    ; Test 2: Parse an identifier expression
    parser := Parser(\"foo\")
    choose parser.parse_name()
        when err: Error
            return 3
        when name: Success
        {
            if ~parser.is_at_end()
                return 4
        }

    ; Test 3: Parse a function definition
    parser := Parser(\"function hello() returns int 42\")
    choose parser.parse_function()
        when err: Error
            return 5
        when func: Success
        {
            if ~parser.is_at_end()
                return 6
        }

    ; Test 4: Parse a structure definition
    parser := Parser(\"define a ()\")
    choose parser.parse_definition()
        when err: Error
            return 7
        when def: Success
        {
            if ~parser.is_at_end()
                return 8
        }

    ; Test 5: Parse a structure with properties
    parser := Parser(\"define Point (x: int, y: int)\")
    choose parser.parse_definition()
        when err: Error
            return 9
        when def: Success
        {
            if ~parser.is_at_end()
                return 10
        }

    ; Test 6: Parse a union definition
    parser := Parser(\"define Option union (Some: int, None)\")
    choose parser.parse_definition()
        when err: Error
            return 11
        when def: Success
        {
            if ~parser.is_at_end()
                return 12
        }

    0
}
}

"

))
]]>
