<![CDATA[
;; Generate Scaly Parser from scaly.sgm

;; Helper to generate char constant name from punctuation value
;; Returns function call syntax like ParserConstants.CHAR_LPAREN()
(define (punct-const-name value)
    (case value
        (("(") "ParserConstants.CHAR_LPAREN()")
        ((")") "ParserConstants.CHAR_RPAREN()")
        (("[") "ParserConstants.CHAR_LBRACKET()")
        (("]") "ParserConstants.CHAR_RBRACKET()")
        (("{") "ParserConstants.CHAR_LBRACE()")
        (("}") "ParserConstants.CHAR_RBRACE()")
        ((",") "ParserConstants.CHAR_COMMA()")
        ((".") "ParserConstants.CHAR_DOT()")
        (("!") "ParserConstants.CHAR_EXCL()")
        (("?") "ParserConstants.CHAR_QUESTION()")
        (("#") "ParserConstants.CHAR_HASH()")
        (("$") "ParserConstants.CHAR_DOLLAR()")
        (("^") "ParserConstants.CHAR_CARET()")
        (("\\\\") "ParserConstants.CHAR_BACKSLASH()")
        (else ($ "ParserConstants.CHAR_" value "()"))))

(define (generate-parser-scaly) ($
"; parser.scaly - Generated from scaly.sgm
; DO NOT EDIT - generated by codegen

use scaly.containers.String
use scaly.containers.Vector
use scaly.memory.Page
use scaly.containers.Array
use scaly.containers.List
use scaly.containers.HashSet
use scaly.containers.HashSetBuilder

define parser
{
; Parser error types
define DifferentSyntax()
define InvalidSyntax(start: size_t, end: size_t, message: String)

define ParserError union (
    Different: DifferentSyntax
    Invalid: InvalidSyntax
)

; Syntax types are defined in Syntax.scaly (loaded as module Syntax by compiler.scaly)

; Lexer import (uses its own char constants)
module lexer

; Character constants for punctuation (char literals use double-quote + type annotation)
define ParserConstants
{
    function CHAR_LPAREN() returns char
        \"(\" as char
    function CHAR_RPAREN() returns char
        \")\" as char
    function CHAR_LBRACKET() returns char
        \"[\" as char
    function CHAR_RBRACKET() returns char
        \"]\" as char
    function CHAR_LBRACE() returns char
        \"{\" as char
    function CHAR_RBRACE() returns char
        \"}\" as char
    function CHAR_COMMA() returns char
        \",\" as char
    function CHAR_DOT() returns char
        \".\" as char
    function CHAR_EXCL() returns char
        \"!\" as char
    function CHAR_QUESTION() returns char
        \"?\" as char
    function CHAR_HASH() returns char
        \"#\" as char
    function CHAR_DOLLAR() returns char
        \"$\" as char
    function CHAR_CARET() returns char
        \"^\" as char
    function CHAR_BACKSLASH() returns char
        \"\\\\\" as char
}

define Parser
(
    lexer: Lexer
    keywords_index: Vector[String]
    keywords: HashSet[String]
)
{
    init#(rp, text: String)
    {
        set lexer: Lexer(text)
        set keywords_index: initialize_keywords_index#()
        set keywords: initialize_keywords#()
    }

    function initialize_keywords_index#(rp, this: Parser) returns Vector[String]
    {
        var keywords_builder Array[String]()
"   (apply-to-selected-children "keyword" (lambda (keyword) ($
"        keywords_builder.add(String#(\""(id keyword)"\"))
"   )))
"        Vector[String]#(keywords_builder)
    }

    function initialize_keywords#(rp, this: Parser) returns HashSet[String]
    {
        var hash_set_builder HashSetBuilder[String](keywords_index)
        HashSet[String]#(hash_set_builder)
    }

    function parse_literal_token#(rp, this: Parser) returns Literal throws ParserError
    {
        choose lexer.token
            when empty: Empty
                lexer.advance#()
            else {}

        choose lexer.token
            when literal: Literal
            {
                ; Deep-copy the String payload onto rp so the literal survives
                ; future lexer token allocations that might reuse the same
                ; memory. Lexer scan_* procedures allocate Strings without an
                ; explicit page - those allocations go on ephemeral pages that
                ; can be reclaimed and overwritten by later parse phases.
                var ret_deep: Literal
                choose literal.value
                    when il: IntegerLiteral
                        set ret_deep: Literal.Integer(IntegerLiteral(String#(il.value.get_buffer(), il.value.get_length())))
                    when sl: StringLiteral
                        set ret_deep: Literal.String(StringLiteral(String#(sl.value.get_buffer(), sl.value.get_length())))
                    when cl: CharacterLiteral
                        set ret_deep: Literal.Character(CharacterLiteral(String#(cl.value.get_buffer(), cl.value.get_length())))
                    when fl: FragmentLiteral
                        set ret_deep: Literal.Fragment(FragmentLiteral(String#(fl.value.get_buffer(), fl.value.get_length())))
                    when fp: FloatingPointLiteral
                        set ret_deep: Literal.FloatingPoint(FloatingPointLiteral(String#(fp.value.get_buffer(), fp.value.get_length())))
                    when hl: HexLiteral
                        set ret_deep: Literal.Hex(HexLiteral(String#(hl.value.get_buffer(), hl.value.get_length())))
                    else
                        set ret_deep: literal.value
                lexer.empty()
                return ret_deep
            }
            else
                throw ParserError.Different(DifferentSyntax())
    }
"
    (apply-to-selected-children "syntax" (lambda (syntax) ($
        (if (multiple? syntax) ($
"
    function parse_"(downcase-string (id syntax))"_list#(rp, this: Parser) returns ref[Vector["(id syntax)"Syntax]]? throws ParserError
    {
        var acc List["(id syntax)"Syntax]()
        var parsing: bool true
        while parsing
        {
            choose parse_"(downcase-string (id syntax))"#()
                when err: Error
                {
                    ; Different = no more items; stop the list (or rethrow if the
                    ; list is still empty, so the caller sees Different). Invalid =
                    ; an item committed then hit a real syntax error; propagate it
                    ; instead of silently truncating the list (e.g. a no-else if).
                    choose err
                        when i: Invalid
                            throw ParserError.Invalid(i)
                        when d: Different
                        {
                            if acc.head = null
                                throw err
                            set parsing: false
                        }
                }
                when node: Success
                    acc.add(node)
        }
        Vector["(id syntax)"Syntax]#(acc)
    }
"       ) "")
"
    function parse_"(downcase-string (id syntax))"#(rp, this: Parser) returns "(id syntax)"Syntax throws ParserError
    {
"       (if (abstract? syntax)
            ;; Abstract syntax - try each alternative
            ($
                (apply-to-children-of syntax (lambda (content) ($
"        choose parse_"(downcase-string (link content))"#()
            when err: Error
            {
                choose err
                    when i: Invalid
                        throw ParserError.Invalid(i)
                    when d: Different {}
            }
            when node: Success
                return "(id syntax)"Syntax."(link content)"(node)
"
                )))
"        throw ParserError.Different(DifferentSyntax())
"
            )
            ;; Concrete syntax - parse each field
            ($
"        let start lexer.previous_position
"               (if (peek? syntax) ($
"        var snapshot lexer.save_state()
        lexer.parse_colon#()
"               ) "")
                (apply-to-children-of syntax (lambda (content)
                    (case (type content)
                        (("syntax")
                            (if (property content)
                            (let ((prop (property content))
                                  (type-name (if (multiple? content)
                                                 ($ "ref[Vector[" (link content) "Syntax]]?")
                                                 ($ (link content) "Syntax"))))
                            (if (optional? content)
                                ($
"
        let " prop "_start lexer.position
        var " prop ": ref[" (if (multiple? content) ($ "Vector[" (link content) "Syntax]") ($ (link content) "Syntax")) "]? null
        choose parse_"(downcase-string (link content))(if (multiple? content) "_list" "")"#()
            when err: Error
            {
                choose err
                    when d: Different {}
                    when i: Invalid"
                                    (if (multiple? content)
"
                        throw ParserError.Invalid(i)"
" {}")
"
            }
            when success: Success
                set " prop ": "
                                    (if (multiple? content)
                                        "success"
                                        (let ((target (element-with-id (link content))))
                                            (if (abstract? target)
                                                ($ (link content) "Syntax#(success)")
                                                ($ (link content) "Syntax#(success.start, success.end"
                                                   (apply-to-nodelist (properties target)
                                                       (lambda (p) ($ ", success." (property p))))
                                                   ")"))))
"
"
                                )
                                ;; non-optional syntax
                                ($
"
        let " prop "_start lexer.position
        var " prop ": " type-name "
        choose parse_"(downcase-string (link content))(if (multiple? content) "_list" "")"#()
            when err: Error
"
                                    (if (equal? 1 (child-number content))
                                        "                throw err
"
                                        ($
"            {
                choose err
                    when d: Different
                        throw ParserError.Invalid(InvalidSyntax(" prop "_start, lexer.position, String#(\"expected "(link content)"\")))
                    when i: Invalid
                        throw ParserError.Invalid(i)
            }
"
                                        )
                                    )
"            when success: Success
                set " prop ": success
"
                                )
                            )) "")  ; close (if optional), (let), else "", close (if property)
                        )
                        (("literal")
                            (let ((prop (property content)))
                            ($
"
        var " prop ": Literal
        choose parse_literal_token#()
            when err: Error
                throw err
            when success: Success
                set " prop ": success
"
                            ))
                        )
                        (("keyword")
                            ($
"
        if ~lexer.parse_keyword#(String#(\""(id (element-with-id (link content)))"\"))"
                                (if (equal? 1 (child-number content))
                                    (if (peek? syntax)
                                        "
        {
            lexer.restore_state(snapshot)
            throw ParserError.Different(DifferentSyntax())
        }
"
                                        "
            throw ParserError.Different(DifferentSyntax())
")
                                    ($ "
            throw ParserError.Invalid(InvalidSyntax(start, lexer.position, String#(\"expected '"(id (element-with-id (link content)))"'\")))
")
                                )
                            )
                        )
                        (("punctuation")
                            (if (optional? content)
                                ;; Optional punctuation - just try it
                                ($
"
        lexer.parse_punctuation#("(punct-const-name (value (element-with-id (link content))))")
"                               )
                                ;; Required punctuation
                                ($
"
        if ~lexer.parse_punctuation#("(punct-const-name (value (element-with-id (link content))))")"
                                    (if (equal? 1 (child-number content))
                                        "
            throw ParserError.Different(DifferentSyntax())
"
                                        ($ "
            throw ParserError.Invalid(InvalidSyntax(start, lexer.position, String#(\"expected '"(value (element-with-id (link content)))"'\")))
")
                                    )
                                )
                            )
                        )
                        (("colon")
                            (if (optional? content)
                                ;; Optional colon - just try it
                                ($
"
        lexer.parse_colon#()
"                               )
                                ;; Required colon
                                ($
"
        if ~lexer.parse_colon#()"
                                    (if (equal? 1 (child-number content))
                                        "
            throw ParserError.Different(DifferentSyntax())
"
                                        "
            throw ParserError.Invalid(InvalidSyntax(start, lexer.position, String#(\"expected colon or newline\")))
")
                                )
                            )
                        )
                        (("identifier")
                            (let ((prop (property content)))
                            ($
"
        let " prop " lexer.parse_identifier#(keywords)
        if " prop ".length() = 0"
                                (if (equal? 1 (child-number content))
                                    "
            throw ParserError.Different(DifferentSyntax())
"
                                    "
            throw ParserError.Invalid(InvalidSyntax(start, lexer.position, String#(\"expected identifier\")))
")
                            ))
                        )
                        (("attribute")
                            (let ((prop (property content)))
                            ($
"
        let " prop " lexer.parse_attribute#()
        if " prop ".length() = 0"
                                (if (equal? 1 (child-number content))
                                    "
            throw ParserError.Different(DifferentSyntax())
"
                                    "
            throw ParserError.Invalid(InvalidSyntax(start, lexer.position, String#(\"expected attribute\")))
")
                            ))
                        )
                        (else "")
                    )
                ))
"
        let end lexer.position

        "(id syntax)"Syntax(start, end"
                (apply-to-property-children-of syntax (lambda (content) ($
                    ", "
                    (if (or (equal? (type content) "keyword") (equal? (type content) "punctuation"))
                        "true"
                        (if (and (equal? (type content) "syntax") (not (multiple? content)) (not (optional? content)) (is-recursive-ref? syntax content))
                            ($ (link content)"Syntax#("(property content)")")
                            (property content)))
                )))
                ")
"
            )
        )
"    }
"   )))
"
    function is_at_end(this: Parser) returns bool
        lexer.is_at_end()
}

function test() returns int
{
    ; Test 1: Parse a simple literal
    var parser Parser(String(\"42\"))
    choose parser.parse_literal$()
        when err: Error
            return 1
        when literal: Success
        {
            if ~parser.is_at_end()
                return 2
        }

    ; Test 2: Parse an identifier expression
    set parser: Parser(String(\"foo\"))
    choose parser.parse_name$()
        when err: Error
            return 3
        when name: Success
        {
            if ~parser.is_at_end()
                return 4
        }

    ; Test 3: Parse a function definition
    set parser: Parser(String(\"function hello() returns int 42\"))
    choose parser.parse_function$()
        when err: Error
            return 5
        when func: Success
        {
            if ~parser.is_at_end()
                return 6
        }

    ; Test 4: Parse a structure definition
    set parser: Parser(String(\"define a ()\"))
    choose parser.parse_definition$()
        when err: Error
            return 7
        when def: Success
        {
            if ~parser.is_at_end()
                return 8
        }

    ; Test 5: Parse a structure with properties
    set parser: Parser(String(\"define Point (x: int, y: int)\"))
    choose parser.parse_definition$()
        when err: Error
            return 9
        when def: Success
        {
            if ~parser.is_at_end()
                return 10
        }

    ; Test 6: Parse a union definition
    set parser: Parser(String(\"define Option union (Some: int, None)\"))
    choose parser.parse_definition$()
        when err: Error
            return 11
        when def: Success
        {
            if ~parser.is_at_end()
                return 12
        }

    0
}
}

"

))
]]>
