<![CDATA[
;; Generate Syntax.scaly from scaly.sgm
;; Converts Scaly syntax definitions to Scaly language types

(define (generate-syntax-scaly) ($
"; Syntax.scaly - Generated from scaly.sgm
; DO NOT EDIT - generated by codegen

use scaly.containers.String
use scaly.containers.Vector

; ============================================================================
; Literal types
; ============================================================================

define IdentifierLiteral(name: String)
define StringLiteral(value: String)
define CharacterLiteral(value: String)
define FragmentLiteral(value: String)
define IntegerLiteral(value: String)
define BooleanLiteral(value: bool)
define FloatingPointLiteral(value: String)
define HexLiteral(value: String)

define Literal union (
    String: StringLiteral
    Character: CharacterLiteral
    Fragment: FragmentLiteral
    Integer: IntegerLiteral
    Boolean: BooleanLiteral
    FloatingPoint: FloatingPointLiteral
    Hex: HexLiteral
)

; ============================================================================
; Syntax node definitions
; ============================================================================
"
    (apply-to-nodelist (node-list-reverse (select-elements (children (current-node)) "syntax")) (lambda (syntax-node)
        (if (not (abstract? syntax-node))
            ;; Concrete syntax - generate struct
            ($
"
define "(id syntax-node)"Syntax
(
    start: size_t
    end: size_t"
                (apply-to-children-of syntax-node (lambda (content) ($
                    (if (property content) ($
"
    "(property content)": "
                        (case (type content)
                            (("syntax") ($
                                (if (multiple? content)
                                    ($ "pointer[Vector["(link content)"Syntax]]")
                                    (if (optional? content)
                                        ($ "pointer["(link content)"Syntax]")
                                        ($ (link content)"Syntax")))))
                            (("identifier" "attribute") "String")
                            (("literal") "Literal")
                            (("keyword" "punctuation" "colon") "bool")
                            (else "; unknown")
                        )
                    )"")
                )))
"
)
"           )
            ;; Abstract syntax - generate union
            ($
"
define "(id syntax-node)"Syntax union ("
                (apply-to-children-of syntax-node (lambda (content) ($
"
    "(link content)": "(link content)"Syntax"
                )))
"
)
"           )
        )
    ))
))
]]>
