<![CDATA[
;; Generate C++ Syntax.h from scaly.sgm
;; Converts Scaly syntax definitions to idiomatic C++ with std::variant

;; Helper to join a list with separator
(define (join-with-comma items)
    (if (null? items)
        ""
        (if (null? (cdr items))
            (car items)
            (string-append (car items) ", " (join-with-comma (cdr items))))))

(define (generate-syntax-cpp) ($
"// Syntax.h - Generated from scaly.sgm
// DO NOT EDIT - generated by codegen

#pragma once

#include \"Lexer.h\"
#include \"llvm/ADT/StringRef.h\"
#include <cstddef>
#include <variant>
#include <vector>

namespace scaly {

// Forward declarations for all syntax types
"
    (apply-to-nodelist (select-elements (children (current-node)) "syntax") (lambda (syntax-node)
        ($ "struct "(id syntax-node)"Syntax;
")
    ))
"
// Parser error types
struct DifferentSyntax {};
struct InvalidSyntax {
    size_t Start;
    size_t End;
    llvm::StringRef Message;
};

using ParserError = std::variant<DifferentSyntax, InvalidSyntax>;

// Syntax node definitions
"
    (apply-to-nodelist (node-list-reverse (select-elements (children (current-node)) "syntax")) (lambda (syntax-node)
        (if (not (abstract? syntax-node))
            ;; Concrete syntax - generate struct
            ($
"
struct "(id syntax-node)"Syntax {
    size_t Start;
    size_t End;"
                (apply-to-children-of syntax-node (lambda (content) ($
                    (if (property content) ($
"
    "
                        (case (type content)
                            (("syntax") ($
                                (if (multiple? content)
                                    ($ "std::vector<"(link content)"Syntax>*")
                                    (if (optional? content)
                                        ($ (link content)"Syntax*")
                                        (if (is-recursive-ref? syntax-node content)
                                            ($ "std::unique_ptr<"(link content)"Syntax>")
                                            ($ (link content)"Syntax"))))))
                            (("identifier" "attribute")
                                "llvm::StringRef")
                            (("literal") "Literal")
                            (("keyword" "punctuation" "colon") "bool")
                            (else "/* unknown */")
                        )
                        " "(property content)";"
                    )"")
                )))
"
};
"           )
            ;; Abstract syntax - generate wrapper struct with variant
            ($
"
struct "(id syntax-node)"Syntax {
    std::variant<"
                (join-with-comma
                    (map (lambda (content) ($ (link content)"Syntax"))
                         (node-list->list (children syntax-node))))
"> Value;
};
"           )
        )
    ))
"
} // namespace scaly
"
))

;; Generate SyntaxDump.h - JSON serialization for AST nodes
(define (generate-syntax-dump-cpp) ($
"// SyntaxDump.h - Generated from scaly.sgm
// DO NOT EDIT - generated by codegen
// JSON serialization for AST inspection

#pragma once

#include \"Syntax.h\"
#include \"llvm/Support/raw_ostream.h\"
#include <string>

namespace scaly {

class SyntaxDumper {
    llvm::raw_ostream &OS;
    int Indent = 0;

    void indent() { for (int i = 0; i < Indent; i++) OS << \"  \"; }
    void nl() { OS << \"\\n\"; }

    void key(const char *k) { indent(); OS << \"\\\"\" << k << \"\\\": \"; }
    void strVal(llvm::StringRef s) {
        OS << \"\\\"\";
        for (char c : s) {
            if (c == '\"') OS << \"\\\\\\\"\";
            else if (c == '\\\\') OS << \"\\\\\\\\\";
            else if (c == '\\n') OS << \"\\\\n\";
            else if (c == '\\r') OS << \"\\\\r\";
            else if (c == '\\t') OS << \"\\\\t\";
            else OS << c;
        }
        OS << \"\\\"\";
    }

public:
    SyntaxDumper(llvm::raw_ostream &os) : OS(os) {}

    void dumpSpan(size_t Start, size_t End) {
        key(\"start\"); OS << Start << \",\"; nl();
        key(\"end\"); OS << End;
    }

"
    ;; Generate dump method for each syntax node
    (apply-to-nodelist (node-list-reverse (select-elements (children (current-node)) "syntax")) (lambda (syntax-node)
        (if (not (abstract? syntax-node))
            ;; Concrete syntax - generate struct dumper
            ($
"    void dump(const "(id syntax-node)"Syntax &N) {
        OS << \"{\"; nl(); Indent++;
        key(\"node\"); OS << \"\\\""(id syntax-node)"\\\",\"; nl();
        dumpSpan(N.Start, N.End);"
                (apply-to-children-of syntax-node (lambda (content) ($
                    (if (property content)
                        (case (type content)
                            (("syntax") ($
                                (if (multiple? content)
                                    ;; multiple syntax: vector pointer
                                    ($ "
        if (N."(property content)") {
            OS << \",\"; nl();
            key(\""(property content)"\"); OS << \"[\"; nl(); Indent++;
            for (size_t i = 0; i < N."(property content)"->size(); i++) {
                indent(); dump((*N."(property content)")[i]);
                if (i + 1 < N."(property content)"->size()) OS << \",\";
                nl();
            }
            Indent--; indent(); OS << \"]\";
        }")
                                    (if (optional? content)
                                        ;; optional syntax: pointer
                                        ($ "
        if (N."(property content)") {
            OS << \",\"; nl();
            key(\""(property content)"\"); dump(*N."(property content)");
        }")
                                        ;; required syntax: value or unique_ptr
                                        (if (is-recursive-ref? syntax-node content)
                                            ($ "
        OS << \",\"; nl();
        key(\""(property content)"\"); dump(*N."(property content)");")
                                            ($ "
        OS << \",\"; nl();
        key(\""(property content)"\"); dump(N."(property content)");")
                                        )))))
                            (("identifier" "attribute") ($
"
        OS << \",\"; nl();
        key(\""(property content)"\"); strVal(N."(property content)");"))
                            (("literal") ($
"
        OS << \",\"; nl();
        key(\""(property content)"\"); dumpLiteral(N."(property content)");"))
                            (("keyword" "punctuation" "colon") ($
"
        OS << \",\"; nl();
        key(\""(property content)"\"); OS << (N."(property content)" ? \"true\" : \"false\");"))
                            (else ""))
                        "")
                )))
"
        nl(); Indent--; indent(); OS << \"}\";
    }
"           )
            ;; Abstract syntax - generate variant dumper
            ($
"    void dump(const "(id syntax-node)"Syntax &N) {
        std::visit([this](const auto &V) { dump(V); }, N.Value);
    }
"           )
        )
    ))
"
    // Literal dumper
    void dumpLiteral(const Literal &L) {
        std::visit([this](const auto &V) {
            using T = std::decay_t<decltype(V)>;
            if constexpr (std::is_same_v<T, StringLiteral>) {
                OS << \"{\\\"type\\\": \\\"string\\\", \\\"value\\\": \"; strVal(V.Value); OS << \"}\";
            } else if constexpr (std::is_same_v<T, IntegerLiteral>) {
                OS << \"{\\\"type\\\": \\\"integer\\\", \\\"value\\\": \"; strVal(V.Value); OS << \"}\";
            } else if constexpr (std::is_same_v<T, FloatingPointLiteral>) {
                OS << \"{\\\"type\\\": \\\"float\\\", \\\"value\\\": \"; strVal(V.Value); OS << \"}\";
            } else if constexpr (std::is_same_v<T, BooleanLiteral>) {
                OS << \"{\\\"type\\\": \\\"boolean\\\", \\\"value\\\": \" << (V.Value ? \"true\" : \"false\") << \"}\";
            } else if constexpr (std::is_same_v<T, HexLiteral>) {
                OS << \"{\\\"type\\\": \\\"hex\\\", \\\"value\\\": \"; strVal(V.Value); OS << \"}\";
            } else if constexpr (std::is_same_v<T, CharacterLiteral>) {
                OS << \"{\\\"type\\\": \\\"character\\\", \\\"value\\\": \"; strVal(V.Value); OS << \"}\";
            } else if constexpr (std::is_same_v<T, FragmentLiteral>) {
                OS << \"{\\\"type\\\": \\\"fragment\\\", \\\"value\\\": \"; strVal(V.Value); OS << \"}\";
            }
        }, L);
    }

};

} // namespace scaly
"
))
]]>