(define (generate-syntax) ($
"// Syntax types generated from scaly.sgm
// DO NOT EDIT - generated by codegen

export interface Span {
  start: number
  end: number
}
"
   (apply $ (map
        (lambda (tag payload type) ($
"
export interface "tag"Literal extends Span {
  _syntax: '"tag"Literal'
  "payload": "type"
}
"       ))
        (list "Identifier" "String" "Character" "Fragment" "Integer" "Boolean" "FloatingPoint" "Hex")
        (list "name"       "value"  "value"     "value"    "value"   "value"   "value"         "value")
        (list "string"     "string" "string"    "string"   "string"  "boolean" "string"        "string")
    ))
"
export type Literal =
"   (apply $ (map
        (lambda (tag) ($
"  | "tag"Literal
"       ))
        (list "String" "Character" "Fragment" "Integer" "Boolean" "FloatingPoint" "Hex")
    ))
    (apply-to-nodelist (node-list-reverse (select-elements (children (current-node)) "syntax")) (lambda (syntax-node)
        (if (not (abstract? syntax-node))
            ($
"
export interface "(id syntax-node)"Syntax extends Span {
  _syntax: '"(id syntax-node)"Syntax'"
                (apply-to-children-of syntax-node (lambda (content) ($
                    (if (property content) ($
"
  "
                        (property content)
": "
                        (case (type content)
                            (("syntax") ($ (link content)"Syntax"(if (multiple? content) "[]" "")(if (optional? content) " | null" "")))
                            (("identifier" "attribute") ($ "string"(if (optional? content) " | null" "")))
                            (("literal") "Literal")
                            (("keyword" "punctuation" "colon") "boolean")
                            (else "unknown")
                        )
                    )"")
                )))
"
}
"           )
            ($
"
export type "(id syntax-node)"Syntax =
"   (apply-to-children-of syntax-node (lambda (content) ($
"  | "(link content)"Syntax
"               )))
           )
        )
    ))
))
