<![CDATA[
;; Generate C++ Syntax.h from scaly.sgm
;; Converts Scaly syntax definitions to idiomatic C++ with std::variant

;; Helper to join a list with separator
(define (join-with-comma items)
    (if (null? items)
        ""
        (if (null? (cdr items))
            (car items)
            (string-append (car items) ", " (join-with-comma (cdr items))))))

(define (generate-syntax-cpp) ($
"// Syntax.h - Generated from scaly.sgm
// DO NOT EDIT - generated by codegen

#pragma once

#include \"Lexer.h\"
#include \"llvm/ADT/StringRef.h\"
#include <cstddef>
#include <variant>
#include <vector>

namespace scaly {

// Forward declarations for all syntax types
"
    (apply-to-nodelist (select-elements (children (current-node)) "syntax") (lambda (syntax-node)
        ($ "struct "(id syntax-node)"Syntax;
")
    ))
"
// Parser error types
struct DifferentSyntax {};
struct InvalidSyntax {
    size_t Start;
    size_t End;
    llvm::StringRef Message;
};

using ParserError = std::variant<DifferentSyntax, InvalidSyntax>;

// Syntax node definitions
"
    (apply-to-nodelist (node-list-reverse (select-elements (children (current-node)) "syntax")) (lambda (syntax-node)
        (if (not (abstract? syntax-node))
            ;; Concrete syntax - generate struct
            ($
"
struct "(id syntax-node)"Syntax {
    size_t Start;
    size_t End;"
                (apply-to-children-of syntax-node (lambda (content) ($
                    (if (property content) ($
"
    "
                        (case (type content)
                            (("syntax") ($
                                (if (multiple? content)
                                    ($ "std::vector<"(link content)"Syntax>*")
                                    (if (optional? content)
                                        ($ (link content)"Syntax*")
                                        ($ (link content)"Syntax")))))
                            (("identifier" "attribute")
                                "llvm::StringRef")
                            (("literal") "Literal")
                            (("keyword" "punctuation" "colon") "bool")
                            (else "/* unknown */")
                        )
                        " "(string-firstchar-upcase (property content))";"
                    )"")
                )))
"
};
"           )
            ;; Abstract syntax - generate wrapper struct with variant
            ($
"
struct "(id syntax-node)"Syntax {
    std::variant<"
                (join-with-comma
                    (map (lambda (content) ($ (link content)"Syntax"))
                         (node-list->list (children syntax-node))))
"> Value;
};
"           )
        )
    ))
"
} // namespace scaly
"
))
]]>