<![CDATA[; testdoc.scm - Generate DocBook documentation from test.dtd documents

(define (generate-testdoc) ($
"<!-- Generated test documentation from tests.sgm -->
<!-- DO NOT EDIT - generated by codegen -->

<section xmlns='http://docbook.org/ns/docbook' xml:id='generated-tests'>
  <title>Test Cases</title>
"
    (apply-to-selected-children "tests" (lambda (tests) ($
"
  <section xml:id='tests-"(attribute-string "xml:id" tests)"'>
    <title>"(attribute-string "title" tests)"</title>
    <informaltable>
      <tgroup cols='2'>
        <colspec colwidth='1*'/>
        <colspec colwidth='1*'/>
        <thead>
          <row>
            <entry>Input</entry>
            <entry>Result</entry>
          </row>
        </thead>
        <tbody>
"
        (apply-to-selected-children-of tests "test" (lambda (test) ($
"          <row>
            <entry><literal>"(test-input-doc test)"</literal></entry>
            <entry><literal>"(test-expect-doc test)"</literal></entry>
          </row>
"
        )))
"        </tbody>
      </tgroup>
    </informaltable>
  </section>
"
    )))
"
</section>
"
))

; Get input for documentation (escape XML special chars)
(define (test-input-doc test)
    (escape-xml (trim (data (node-list-first (select-elements (children test) "input"))))))

; Get expect for documentation (escape XML special chars)
(define (test-expect-doc test)
    (escape-xml (trim (data (node-list-first (select-elements (children test) "expect"))))))

; Escape XML special characters
(define (escape-xml s)
    (list->string
        (apply append
            (map (lambda (c)
                    (cond
                        ((char=? c #\&) (string->list "&amp;"))
                        ((char=? c #\<) (string->list "&lt;"))
                        ((char=? c #\>) (string->list "&gt;"))
                        (else (list c))))
                 (string->list s)))))

; trim and drop-leading-ws are defined in testjs.scm
]]>