<![CDATA[; testdoc.scm - Generate DocBook documentation from test.dtd documents

(define (generate-testdoc) ($
"<!-- Generated documentation from tests.sgm -->
<!-- DO NOT EDIT - generated by codegen -->
"
    (apply-to-selected-children "category" (lambda (category) ($
"
  <section xmlns='http://docbook.org/ns/docbook' xml:id='category-"(id category)"'>
    <title>"(attribute-string "title" category)"</title>
    <para>"(category-prose category)"</para>
"
        (apply-to-selected-children-of category "tests" (lambda (tests) ($
"
    <section xml:id='tests-"(id tests)"'>
      <title>"(attribute-string "title" tests)"</title>
      <para>"(tests-prose tests)"</para>
      <informaltable frame='none'>
        <tgroup cols='2'>
          <colspec colwidth='1*'/>
          <colspec colwidth='1*'/>
          <thead>
            <row>
              <entry>Input</entry>
              <entry>Result</entry>
            </row>
          </thead>
          <tbody>
"
            (apply-to-selected-children-of tests "test" (lambda (test)
                (if (attribute-string "program" test)
                    ($ "            <row>
              <entry><programlisting>"(test-input-doc test)"</programlisting></entry>
              <entry><literal>"(test-expect-doc test)"</literal></entry>
            </row>
")
                    ($ "            <row>
              <entry><literal>"(test-input-doc test)"</literal></entry>
              <entry><literal>"(test-expect-doc test)"</literal></entry>
            </row>
"))))
"          </tbody>
        </tgroup>
      </informaltable>
    </section>
"
        )))
"  </section>
"
    )))
))

; Get prose from category
(define (category-prose category)
    (let ((prose-node (node-list-first (select-elements (children category) "prose"))))
        (if (node-list-empty? prose-node)
            ""
            (trim (data prose-node)))))

; Get prose from tests element
(define (tests-prose tests)
    (let ((prose-node (node-list-first (select-elements (children tests) "prose"))))
        (if (node-list-empty? prose-node)
            ""
            (trim (data prose-node)))))

; Get input for documentation (escape XML special chars)
(define (test-input-doc test)
    (escape-xml (test-input test)))

; Get expect for documentation (escape XML special chars)
(define (test-expect-doc test)
    (escape-xml (test-expect test)))

; Escape XML special characters
(define (escape-xml s)
    (list->string
        (apply append
            (map (lambda (c)
                    (cond
                        ((char=? c #\&) (string->list "&amp;"))
                        ((char=? c #\<) (string->list "&lt;"))
                        ((char=? c #\>) (string->list "&gt;"))
                        (else (list c))))
                 (string->list s)))))

; test-input, test-expect, trim and drop-leading-ws are defined in testjs.scm
]]>
