<![CDATA[; testscaly.scm - Generate self-hosted AOT test programs from test.dtd documents
; Emits one standalone .scaly program per test under tests/selfhosted/.
; Value tests (int/bool) print PASS or FAIL; string/char/json/float tests are
; compile-only (mode: compile in the header), matching the C++ JIT harness
; for string/char/json. Floats are compile-only because stage-0's AOT planner
; cannot plan float comparisons yet (float < hangs, float = infers double);
; upgrade them to run tests once that works. Compile-only tests are checked
; with --plan --no-prelude (= the JIT harness's compileToPlan: no prelude,
; no emission - bare union variants like None don't emit as dropped values).
; Run them with tests/selfhosted/run.sh <stage-binary>.
; Requires testcpp.scm to be included first (trim, test-input, test-expect,
; test-skip?, expect-type, list-head, is-newline?, id).

(define (sh-list-tail lst n)
    (if (or (null? lst) (<= n 0))
        lst
        (sh-list-tail (cdr lst) (- n 1))))

; Position of the last newline in the char list, or #f
(define (sh-last-newline chars i last)
    (cond
        ((null? chars) last)
        ((is-newline? (car chars)) (sh-last-newline (cdr chars) (+ i 1) i))
        (else (sh-last-newline (cdr chars) (+ i 1) last))))

; Split input into (prefix-lines . final-expression-line).
; Every literate test keeps its result expression on the last line.
(define (sh-split-input s)
    (let* ((chars (string->list s))
           (pos (sh-last-newline chars 0 #f)))
        (if pos
            (cons (list->string (list-head chars (+ pos 1)))
                  (list->string (sh-list-tail chars (+ pos 1))))
            (cons "" s))))

(define (sh-header suite-name test-id mode expect) ($
"; generated by ./mkp from tests/" suite-name ".sgm - DO NOT EDIT
; test: " test-id "
; mode: " mode "
; expect: " expect "
"))

(define (sh-int-test prefix final expect) ($
prefix
"let literate_result (" final ")
if literate_result = (" expect ")
    print(\"PASS\")
else
    print(\"FAIL\")
"))

(define (sh-bool-test prefix final expect)
    (let ((then-msg (if (string=? expect "true") "PASS" "FAIL"))
          (else-msg (if (string=? expect "true") "FAIL" "PASS")))
        ($
prefix
"let literate_result (" final ")
if literate_result
    print(\"" then-msg "\")
else
    print(\"" else-msg "\")
")))

(define (sh-test-content suite-name test)
    (let* ((test-id (downcase-string (id test)))
           (input (trim (test-input test)))
           (expect (trim (test-expect test)))
           (type (expect-type expect input))
           (split (sh-split-input input))
           (prefix (car split))
           (final (cdr split)))
        (cond
            ((string=? type "bool")
                ($ (sh-header suite-name test-id "run" expect) (sh-bool-test prefix final expect)))
            ((string=? type "int")
                ($ (sh-header suite-name test-id "run" expect) (sh-int-test prefix final expect)))
            (else
                ($ (sh-header suite-name test-id "compile" expect) input "
")))))

(define (generate-selfhosted-test suite-name test)
    (if (test-skip? test)
        (empty-sosofo)
        (file ($ "tests/selfhosted/" suite-name "__" (downcase-string (id test)) ".scaly")
              (sh-test-content suite-name test))))

(define (generate-selfhosted-tests suite-name)
    (apply sosofo-append
        (map (lambda (test) (generate-selfhosted-test suite-name test))
             (node-list->list (select-elements (descendants (current-node)) "test")))))
]]>
