// Generated test cases from tests.sgm
// DO NOT EDIT - generated by codegen

import { describe, it, expect, beforeEach } from 'vitest'
import { evaluate, evaluateProgram, resetEvaluator } from '../src/index.js'

describe('Structure Definitions', () => {
  it('DEFINE-POINT', () => {
    resetEvaluator()
    const result = evaluateProgram(`define Point(x: int, y: int)
Point(3, 4)`)
    expect(result._tag).toBe('Ok')
    expect(JSON.stringify(result.value)).toBe('{"_type":"Point","x":3,"y":4}')
  })
  it('DEFINE-FIELD-ACCESS', () => {
    resetEvaluator()
    const result = evaluateProgram(`define Point(x: int, y: int)
Point(3, 4).x`)
    expect(result._tag).toBe('Ok')
    expect(result.value).toBe(3)
  })
  it('DEFINE-WITH-LET', () => {
    resetEvaluator()
    const result = evaluateProgram(`define Point(x: int, y: int)
let p Point(3, 4)
p.x + p.y`)
    expect(result._tag).toBe('Ok')
    expect(result.value).toBe(7)
  })
  it('DEFINE-NESTED', () => {
    resetEvaluator()
    const result = evaluateProgram(`define Point(x: int, y: int)
define Rectangle(origin: Point, width: int, height: int)
Rectangle(Point(0, 0), 10, 5).width`)
    expect(result._tag).toBe('Ok')
    expect(result.value).toBe(10)
  })
})

