// Generated test cases from tests.sgm
// DO NOT EDIT - generated by codegen

import { describe, it, expect, beforeEach } from 'vitest'
import { evaluate, evaluateProgram, resetEvaluator } from '../src/index.js'

describe('Boolean Literals', () => {
  it('BOOL-TRUE', () => {
    const result = evaluate(`true`)
    expect(result._tag).toBe('Ok')
    expect(result.value).toBe(true)
  })
  it('BOOL-FALSE', () => {
    const result = evaluate(`false`)
    expect(result._tag).toBe('Ok')
    expect(result.value).toBe(false)
  })
})

describe('Integer Literals', () => {
  it('INT-POSITIVE', () => {
    const result = evaluate(`42`)
    expect(result._tag).toBe('Ok')
    expect(result.value).toBe(42)
  })
  it('INT-ZERO', () => {
    const result = evaluate(`0`)
    expect(result._tag).toBe('Ok')
    expect(result.value).toBe(0)
  })
  it('INT-NEGATIVE', () => {
    const result = evaluate(`-7`)
    expect(result._tag).toBe('Ok')
    expect(result.value).toBe(-7)
  })
})

describe('Hexadecimal Literals', () => {
  it('HEX-FF', () => {
    const result = evaluate(`0xFF`)
    expect(result._tag).toBe('Ok')
    expect(result.value).toBe(255)
  })
  it('HEX-1A', () => {
    const result = evaluate(`0x1A`)
    expect(result._tag).toBe('Ok')
    expect(result.value).toBe(26)
  })
  it('HEX-ZERO', () => {
    const result = evaluate(`0x0`)
    expect(result._tag).toBe('Ok')
    expect(result.value).toBe(0)
  })
})

describe('Floating-Point Literals', () => {
  it('FLOAT-PI', () => {
    const result = evaluate(`3.14`)
    expect(result._tag).toBe('Ok')
    expect(result.value).toBe(3.14)
  })
  it('FLOAT-TWO', () => {
    const result = evaluate(`2.0`)
    expect(result._tag).toBe('Ok')
    expect(result.value).toBe(2)
  })
  it('FLOAT-HALF', () => {
    const result = evaluate(`0.5`)
    expect(result._tag).toBe('Ok')
    expect(result.value).toBe(0.5)
  })
})

describe('String Literals', () => {
  it('STRING-HELLO', () => {
    const result = evaluate(`"hello"`)
    expect(result._tag).toBe('Ok')
    expect(result.value).toBe('hello')
  })
  it('STRING-EMPTY', () => {
    const result = evaluate(`""`)
    expect(result._tag).toBe('Ok')
    expect(result.value).toBe('')
  })
})

describe('Character Literals', () => {
  it('CHAR-A', () => {
    const result = evaluate('`a`')
    expect(result._tag).toBe('Ok')
    expect(result.value).toBe('a')
  })
  it('CHAR-Z', () => {
    const result = evaluate('`Z`')
    expect(result._tag).toBe('Ok')
    expect(result.value).toBe('Z')
  })
})

describe('Prefix Functions', () => {
  it('NEGATE-POSITIVE', () => {
    const result = evaluate(`-7`)
    expect(result._tag).toBe('Ok')
    expect(result.value).toBe(-7)
  })
  it('NEGATE-NEGATIVE', () => {
    const result = evaluate(`-(-3)`)
    expect(result._tag).toBe('Ok')
    expect(result.value).toBe(3)
  })
  it('PREFIX-ADD', () => {
    const result = evaluate(`+ 3`)
    expect(result._tag).toBe('Ok')
    expect(result.value).toBe(3)
  })
})

describe('Operator Chains', () => {
  it('SIMPLE-ADD', () => {
    const result = evaluate(`3 + 4`)
    expect(result._tag).toBe('Ok')
    expect(result.value).toBe(7)
  })
  it('SIMPLE-SUBTRACT', () => {
    const result = evaluate(`10 - 3`)
    expect(result._tag).toBe('Ok')
    expect(result.value).toBe(7)
  })
  it('SIMPLE-MULTIPLY', () => {
    const result = evaluate(`6 * 7`)
    expect(result._tag).toBe('Ok')
    expect(result.value).toBe(42)
  })
  it('CHAIN-WITH-PRECEDENCE', () => {
    const result = evaluate(`3 + 4 * 2`)
    expect(result._tag).toBe('Ok')
    expect(result.value).toBe(11)
  })
  it('CHAIN-LEFT-TO-RIGHT', () => {
    const result = evaluate(`20 - 5 - 3`)
    expect(result._tag).toBe('Ok')
    expect(result.value).toBe(12)
  })
})

describe('Parentheses and Grouping', () => {
  it('PARENS-NEGATE', () => {
    const result = evaluate(`5 * (- 2)`)
    expect(result._tag).toBe('Ok')
    expect(result.value).toBe(-10)
  })
  it('PARENS-GROUPING', () => {
    const result = evaluate(`2 * (3 + 4)`)
    expect(result._tag).toBe('Ok')
    expect(result.value).toBe(14)
  })
  it('NESTED-PARENS', () => {
    const result = evaluate(`(2 + 3) * (4 + 1)`)
    expect(result._tag).toBe('Ok')
    expect(result.value).toBe(25)
  })
})

describe('Identifier Shapes', () => {
  it('NAME-AS-OPERATOR', () => {
    const result = evaluate(`10 div 3`)
    expect(result._tag).toBe('Ok')
    expect(result.value).toBe(3)
  })
  it('NAME-AS-FUNCTION', () => {
    const result = evaluate(`abs (- 5)`)
    expect(result._tag).toBe('Ok')
    expect(result.value).toBe(5)
  })
})

describe('Let Bindings', () => {
  it('LET-SIMPLE', () => {
    resetEvaluator()
    const result = evaluateProgram(`let x 5
x`)
    expect(result._tag).toBe('Ok')
    expect(result.value).toBe(5)
  })
  it('LET-USE-BINDING', () => {
    resetEvaluator()
    const result = evaluateProgram(`let x 5
x + 3`)
    expect(result._tag).toBe('Ok')
    expect(result.value).toBe(8)
  })
  it('LET-NESTED', () => {
    resetEvaluator()
    const result = evaluateProgram(`let x 5
let y 3
x + y`)
    expect(result._tag).toBe('Ok')
    expect(result.value).toBe(8)
  })
  it('LET-EXPR-VALUE', () => {
    resetEvaluator()
    const result = evaluateProgram(`let x 2 + 3
x * 2`)
    expect(result._tag).toBe('Ok')
    expect(result.value).toBe(10)
  })
})

