// Generated test cases from tests.sgm
// DO NOT EDIT - generated by codegen

import { describe, it, expect } from 'vitest'
import { evaluate } from '../src/index.js'

describe('Boolean Literals', () => {
  it('bool-true', () => {
    const result = evaluate(`true`)
    expect(result._tag).toBe('Ok')
    expect(result.value).toBe(true)
  })
  it('bool-false', () => {
    const result = evaluate(`false`)
    expect(result._tag).toBe('Ok')
    expect(result.value).toBe(false)
  })
})

describe('Integer Literals', () => {
  it('int-positive', () => {
    const result = evaluate(`42`)
    expect(result._tag).toBe('Ok')
    expect(result.value).toBe(42)
  })
  it('int-zero', () => {
    const result = evaluate(`0`)
    expect(result._tag).toBe('Ok')
    expect(result.value).toBe(0)
  })
  it('int-negative', () => {
    const result = evaluate(`-7`)
    expect(result._tag).toBe('Ok')
    expect(result.value).toBe(-7)
  })
})

describe('Hexadecimal Literals', () => {
  it('hex-ff', () => {
    const result = evaluate(`0xFF`)
    expect(result._tag).toBe('Ok')
    expect(result.value).toBe(255)
  })
  it('hex-1a', () => {
    const result = evaluate(`0x1A`)
    expect(result._tag).toBe('Ok')
    expect(result.value).toBe(26)
  })
  it('hex-zero', () => {
    const result = evaluate(`0x0`)
    expect(result._tag).toBe('Ok')
    expect(result.value).toBe(0)
  })
})

describe('Floating-Point Literals', () => {
  it('float-pi', () => {
    const result = evaluate(`3.14`)
    expect(result._tag).toBe('Ok')
    expect(result.value).toBe(3.14)
  })
  it('float-two', () => {
    const result = evaluate(`2.0`)
    expect(result._tag).toBe('Ok')
    expect(result.value).toBe(2)
  })
  it('float-half', () => {
    const result = evaluate(`0.5`)
    expect(result._tag).toBe('Ok')
    expect(result.value).toBe(0.5)
  })
})

describe('String Literals', () => {
  it('string-hello', () => {
    const result = evaluate(`"hello"`)
    expect(result._tag).toBe('Ok')
    expect(result.value).toBe('hello')
  })
  it('string-empty', () => {
    const result = evaluate(`""`)
    expect(result._tag).toBe('Ok')
    expect(result.value).toBe('')
  })
})

describe('Character Literals', () => {
  it('char-a', () => {
    const result = evaluate('`a`')
    expect(result._tag).toBe('Ok')
    expect(result.value).toBe('a')
  })
  it('char-z', () => {
    const result = evaluate('`Z`')
    expect(result._tag).toBe('Ok')
    expect(result.value).toBe('Z')
  })
})

