<![CDATA[
;; Generate Scaly Syntax definitions from scaly.sgm

(define (generate-syntax-scaly) ($
"; parser.scaly - Generated from scaly.sgm
; DO NOT EDIT - generated by codegen

use scaly.containers.String
use scaly.containers.Vector
use scaly.memory.Page
use scaly.containers.Array
use scaly.containers.List
use scaly.containers.HashSet
use scaly.containers.HashSetBuilder

; Parser error types
define DifferentSyntax()
define InvalidSyntax(start: size_t, end: size_t, message: String)

define ParserError union (
    Different: DifferentSyntax
    Invalid: InvalidSyntax
)

; Syntax types are defined in Syntax.scaly (loaded as module Syntax by compiler.scaly)
"))
]]>
