#!/usr/bin/env python3
"""Generate packages/http/0.1.0/http/HpackTables.scaly from RFC 7541.

usage: tools/hpack/gentables.py <rfc7541.txt>   (https://www.rfc-editor.org/rfc/rfc7541.txt)

Appendix A gives the static table, Appendix B the Huffman code. The code is
canonical (checked here), so a decoder needs per bit length only the first
code, the number of codes and where their symbols start in the symbols
sorted by (length, symbol).
"""
import re, sys

txt = open(sys.argv[1]).read()
a = txt.index('Appendix A.  Static Table Definition')
b = txt.index('Appendix B.  Huffman Code')
static = {int(i): (n, v) for i, n, v in
          re.findall(r'^\s*\|\s*(\d+)\s*\|\s*(\S+)\s*\|\s*(.*?)\s*\|\s*$', txt[a:b], re.M)}
assert sorted(static) == list(range(1, 62)), 'static table incomplete'

codes = {}
for line in txt[b:].split('\n'):
    m = re.search(r'\(\s*(\d+)\)\s+\|[01|]+\s+([0-9a-f]+)\s+\[\s*(\d+)\]', line)
    if m:
        codes[int(m.group(1))] = (int(m.group(2), 16), int(m.group(3)))
    m = re.search(r'EOS \(256\)\s+\|[01|]+\s+([0-9a-f]+)\s+\[\s*(\d+)\]', line)
    if m:
        codes[256] = (int(m.group(1), 16), int(m.group(2)))
assert sorted(codes) == list(range(257)), 'Huffman table incomplete'
assert abs(sum(2.0 ** -l for c, l in codes.values()) - 1.0) < 1e-12

order = sorted(codes, key=lambda s: (codes[s][1], s))
code, prev = 0, codes[order[0]][1]
for s in order:
    c, l = codes[s]
    code <<= l - prev
    prev = l
    assert c == code, 'not canonical'
    code += 1

first, count, offset = [0] * 31, [0] * 31, [0] * 31
for i, s in enumerate(order):
    c, l = codes[s]
    if count[l] == 0:
        first[l], offset[l] = c, i
    count[l] += 1

# The fast path: for every value of the next 11 bits, the symbols whose
# codes follow each other at their front -- one or two, every lowercase
# letter and digit having 5 or 6 bits -- packed as sym1 | sym2 << 8 |
# len1 << 16 | total << 20 | count << 24 (len1 the first code's length,
# total both lengths); 0 when the first code is longer than 11 bits.
PAIR_BITS = 11
by_prefix = {}
for sym, (c, l) in codes.items():
    if l <= PAIR_BITS and sym != 256:
        by_prefix[(l, c)] = sym
def first_symbol(bits, n):
    # the symbol whose code is a prefix of the n-bit value bits
    for l in range(5, n + 1):
        sym = by_prefix.get((l, bits >> (n - l)))
        if sym is not None:
            return sym, l
    return None
pair = [0] * (1 << PAIR_BITS)
for v in range(1 << PAIR_BITS):
    one = first_symbol(v, PAIR_BITS)
    if one is None:
        continue
    s1, l1 = one
    rest = PAIR_BITS - l1
    two = first_symbol(v & ((1 << rest) - 1), rest) if rest >= 5 else None
    if two is None:
        pair[v] = s1 | (l1 << 16) | (l1 << 20) | (1 << 24)
    else:
        s2, l2 = two
        pair[v] = s1 | (s2 << 8) | (l1 << 16) | ((l1 + l2) << 20) | (2 << 24)

def arr(name, typ, vals):
    return f'define {name}: {typ}[] [{", ".join(str(v) for v in vals)}]\n'

def lit(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'

out = ['; GENERATED by tools/hpack/gentables.py from RFC 7541 (Appendix A, the\n',
       '; static table; Appendix B, the Huffman code) -- do not edit.\n\n',
       '; The Huffman code is canonical: the codes of one length are consecutive\n',
       '; from HUFF_FIRST[length], HUFF_COUNT[length] of them, and their symbols\n',
       '; stand at HUFF_SYMBOLS[HUFF_OFFSET[length]...] in code order.\n',
       arr('HUFF_FIRST', 'u32', first), arr('HUFF_COUNT', 'u32', count),
       arr('HUFF_OFFSET', 'u32', offset), arr('HUFF_SYMBOLS', 'u32', order),
       '; The one or two codes at the front of the next 11 bits: sym1 | sym2 << 8 |\n',
       '; len1 << 16 | total << 20 | count << 24; 0 when the first is longer.\n',
       arr('HUFF_PAIR', 'u32', pair),
       '\n; The static table: entry i (1..61) is (static_name(i), static_value(i)).\n',
       'function static_name(i: u64) returns Slice[u8]\n{\n    match i\n']
for i in range(1, 62):
    out.append(f'        case {i}: return {lit(static[i][0])}\n')
out.append('    ""\n}\n\nfunction static_value(i: u64) returns Slice[u8]\n{\n    match i\n')
for i in range(1, 62):
    if static[i][1]:
        out.append(f'        case {i}: return {lit(static[i][1])}\n')
out.append('    ""\n}\n')
open('packages/http/0.1.0/http/HpackTables.scaly', 'w').write(''.join(out))
