#!/usr/bin/env python3
"""Generate packages/http/0.1.0/http/QpackTables.scaly from RFC 9204.

usage: tools/qpack/gentables.py <rfc9204.txt> [nghttp3_qpack.c]
       (https://www.rfc-editor.org/rfc/rfc9204.txt; the optional second file,
       nghttp3's lib/nghttp3_qpack.c, is a cross-check of every entry)

Appendix A gives the static table. A cell the RFC wraps continues on the
next row: joined without a space after a '-' or a '/', with one otherwise
(the break took a space) -- checked entry by entry against nghttp3.
"""
import re, sys

txt = open(sys.argv[1]).read()
first = txt.index('Appendix A.  Static Table')
a = txt.index('Appendix A.  Static Table', first + 10)
b = txt.index('Appendix B.', a)
rows = []
for line in txt[a:b].split('\n'):
    m = re.match(r'^\s*\|\s*(\d*)\s*\|\s*(.*?)\s*\|\s*(.*?)\s*\|\s*$', line)
    if not m:
        continue
    idx, n, v = m.groups()
    if idx:
        rows.append([int(idx), n, v])
    elif rows:
        for k, part in ((1, n), (2, v)):
            if part:
                prev = rows[-1][k]
                rows[-1][k] = prev + part if prev.endswith(('-', '/')) or not prev else prev + ' ' + part
assert [r[0] for r in rows] == list(range(99)), 'static table incomplete'

if len(sys.argv) > 2:
    src = open(sys.argv[2]).read()
    body = src[src.index('static nghttp3_qpack_static_header stable[] = {'):]
    body = body[:body.index('};')]
    theirs = re.findall(r'MAKE_STATIC_HD\(\s*"((?:[^"\\]|\\.)*)"\s*,\s*"((?:[^"\\]|\\.)*)"', body)
    assert len(theirs) == 99, len(theirs)
    for (i, n, v), (tn, tv) in zip(rows, theirs):
        assert (n, v) == (tn, tv.replace('\\"', '"')), (i, n, v, tn, tv)

def lit(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'

out = ['; GENERATED by tools/qpack/gentables.py from RFC 9204 (Appendix A, the\n',
       '; static table; cross-checked against nghttp3) -- do not edit.\n\n',
       '; The static table: entry i (0..98) is (qpack_static_name(i), qpack_static_value(i)).\n',
       'function qpack_static_name(i: u64) returns Slice[u8]\n{\n    match i\n']
for i, n, v in rows:
    out.append(f'        case {i}: return {lit(n)}\n')
out.append('    ""\n}\n\nfunction qpack_static_value(i: u64) returns Slice[u8]\n{\n    match i\n')
for i, n, v in rows:
    if v:
        out.append(f'        case {i}: return {lit(v)}\n')
out.append('    ""\n}\n')
open('packages/http/0.1.0/http/QpackTables.scaly', 'w').write(''.join(out))
print('99 entries, cross-checked' if len(sys.argv) > 2 else '99 entries')
