#!/usr/bin/env python3
"""Build the per-package textslice SPECs for the ASCII-literal campaign.

Input: the deduplicated census detail (`tools/pointer-report.sh` -> detail.txt): every
`param pointer[const_char] fn(p)` site outside the substrate and containers. Output: one
`spec_<package>.py` per package, in textslice's format with `None` as the length (a
BOUNDED VIEW whose offsets stay explicit), minus the EXCLUDED parameters below -- each
excluded for a reason the reader wrote, never by a tool's verdict.

Usage: mkspec.py <detail.txt> <outdir>
"""
import re, sys, os, collections

# (function, parameter) -> reason. A parameter listed here keeps `pointer[const_char]`.
EXCLUDE = {
    # C-origin text: argv0 / getenv / strerror / argv. The value is a C string the OS handed
    # us; its length is not known until strlen, and the `shared` globals it lands in cannot
    # hold a Slice (a constant initializer is required).
    ('set_prog_name', 'prog'): 'argv0 into a shared pointer global',
    ('set_msg_prog', 'prog'): 'argv0 into a shared pointer global',
    ('set_pipeline', 'p'): 'getenv text into a shared pointer global, read by LLVMRunPasses',
    ('split_path_env', 'v'): 'getenv result, null-tested',
    ('parse_env_decimal', 'v'): 'getenv result, null-tested',
    ('env_matches', 'v'): 'getenv result',
    ('parse_i64', 't'): 'getenv result',
    ('append_lit', 's'): 'argv element',
    ('report_open_failure', 'emsg'): 'strerror() text',
    # The opensp message system stores its templates as C strings (MessageFragment /
    # MessageType); converting one door of it converts the system. Out of this campaign.
    ('usage_emit_msg', 'template_lit'): 'message-table text (get_text())',
    ('report_aux', 'aux_text'): 'message system',
    ('keep_message', 'aux_text'): 'message system',
    ('emit_aux_line', 'text_lit'): 'message system',
    ('MessageFragment', 'text'): 'message system init',
    ('MessageType', 'clauses'): 'message system init',
    ('StringC', 'ascii'): 'the pointer init stays; a Slice[char] init is ADDED beside it',
    # scalyc: values whose only destination is a C API that needs the NUL (shape 2).
    ('entry_alloca', 'name'): 'LLVMBuildAlloca name, NUL-terminated C string',
    ('acquire_temp', 'name'): 'forwarded into entry_alloca',
    ('triple_is_coff', 't'): 'LLVMGetDefaultTargetTriple result, null-tested',
    ('save', 'path'): 'scalygpu: fopen() path, NUL-terminated C string',
    ('load', 'path'): 'scalygpu: fopen() path, NUL-terminated C string',
    # Converted BY HAND: a 1-argument method named `get` matches every `.get(i)` in the package
    # by spelling, so the tool's call-site check drowns in noise; the body compares a String key.
    ('get', 'key'): 'json.get -- by hand',
}

# (function, parameter) -> adjacent length parameter: these two carry an explicit length
# beside the pointer, so textslice collapses the PAIR and drops the length at every call.
PAIRS = {
    ('levenshtein_with_max', 's2'): 'n2',
    ('need_collision_check_for_identifier', 'name'): 'name_len',
}

def main():
    detail, out = sys.argv[1], sys.argv[2]
    by_pkg = collections.defaultdict(list)
    excluded = []
    for l in open(detail):
        m = re.match(r'pointer-report: (packages/(\w+)/0\.1\.0/\S+?):(\d+):\d+: param pointer\[const_char\] (\w+)\((\w+)\)', l)
        if not m: continue
        path, pkg, line, fn, p = m.groups()
        if re.search(r'scaly/(memory|containers|io|fiber|cluster)', path): continue
        if (fn, p) in EXCLUDE: excluded.append((pkg, fn, p, EXCLUDE[(fn, p)])); continue
        by_pkg[pkg].append((path, fn, int(line), p, PAIRS.get((fn, p))))
    os.makedirs(out, exist_ok=True)
    for pkg, rows in sorted(by_pkg.items()):
        rows = sorted(set(rows))
        with open(os.path.join(out, f'spec_{pkg}.py'), 'w') as f:
            f.write(f'# ASCII-literal parameters of packages/{pkg}: pointer[const_char] -> Slice[char] (generated by mkspec.py)\n')
            f.write('SPEC = dict(\n    root=%r,\n    params=[\n' % f'packages/{pkg}/0.1.0')
            for r in rows: f.write(f'        {r!r},\n')
            f.write('    ],\n)\n')
        print(f'{pkg}: {len(rows)} params')
    print(f'excluded: {len(excluded)}')
    for e in sorted(set(excluded)): print('  ', e)

if __name__ == '__main__': main()
