# ASCII-literal parameters of packages/scalyls: pointer[const_char] -> Slice[char] (generated by mkspec.py)
SPEC = dict(
    root='packages/scalyls/0.1.0',
    params=[
        ('packages/scalyls/0.1.0/scalyls/diagnostics.scaly', 'key', 888, 'k', None),
        ('packages/scalyls/0.1.0/scalyls/diagnostics.scaly', 'quoted', 899, 's', None),
        ('packages/scalyls/0.1.0/scalyls/format.scaly', 'key', 951, 'k', None),
        ('packages/scalyls/0.1.0/scalyls/json.scaly', 'match_literal', 556, 'lit', None),
        ('packages/scalyls/0.1.0/scalyls/server.scaly', 'key', 1506, 'k', None),
        ('packages/scalyls/0.1.0/scalyls/server.scaly', 'quoted', 1517, 's', None),
        ('packages/scalyls/0.1.0/scalyls/symbols.scaly', 'enclosing_text', 6738, 'kind', None),
        ('packages/scalyls/0.1.0/scalyls/symbols.scaly', 'hover_leaf', 6505, 'kind', None),
        ('packages/scalyls/0.1.0/scalyls/symbols.scaly', 'hover_routine', 6770, 'kind', None),
        ('packages/scalyls/0.1.0/scalyls/symbols.scaly', 'hover_signature', 6785, 'kind', None),
        ('packages/scalyls/0.1.0/scalyls/symbols.scaly', 'key', 906, 'k', None),
        ('packages/scalyls/0.1.0/scalyls/symbols.scaly', 'kind_name_text', 6719, 'kind', None),
        ('packages/scalyls/0.1.0/scalyls/symbols.scaly', 'labeled_type_text', 6869, 'role', None),
        ('packages/scalyls/0.1.0/scalyls/symbols.scaly', 'lens_object', 928, 'command_id', None),
        ('packages/scalyls/0.1.0/scalyls/symbols.scaly', 'routine_detail_text', 3829, 'kind', None),
        ('packages/scalyls/0.1.0/scalyls/symbols.scaly', 'routine_signature_text', 6840, 'kind', None),
        ('packages/scalyls/0.1.0/scalyls/symbols.scaly', 'target_detail_text', 3909, 'kind', None),
        ('packages/scalyls/0.1.0/scalyls/worker.scaly', 'exchange', 821, 'kind', None),
    ],
)
