# ASCII-literal parameters of packages/scalygpu: pointer[const_char] -> Slice[char] (generated by mkspec.py)
SPEC = dict(
    root='packages/scalygpu/0.1.0',
    params=[
        ('packages/scalygpu/0.1.0/scalygpu/gputape.scaly', 'load', 638, 'path', None),
        ('packages/scalygpu/0.1.0/scalygpu/gputape.scaly', 'save', 614, 'path', None),
    ],
)
