# ASCII-literal parameters of packages/opensp: pointer[const_char] -> Slice[char] (generated by mkspec.py)
SPEC = dict(
    root='packages/opensp/0.1.0',
    params=[
        ('packages/opensp/0.1.0/opensp/ArcEngine.scaly', 'declares_base_architecture', 1299, 'pubid', None),
        ('packages/opensp/0.1.0/opensp/CharsetRegistry.scaly', 'canon_eq', 3865, 's', None),
        ('packages/opensp/0.1.0/opensp/ExternalId.scaly', 'field_word_eq', 345, 's', None),
    ],
)
