# ASCII-literal parameters of packages/scalyc: pointer[const_char] -> Slice[char] (generated by mkspec.py)
SPEC = dict(
    root='packages/scalyc/0.1.0',
    params=[
        ('packages/scalyc/0.1.0/scalyc/compiler/Emitter.scaly', 'report_jit_error', 7170, 'ctx', None),
        ('packages/scalyc/0.1.0/scalyc/compiler/Planner.scaly', 'make_primitive_type', 37548, 'mangled', None),
        ('packages/scalyc/0.1.0/scalyc/compiler/Planner.scaly', 'make_primitive_type', 37548, 'name', None),
        ('packages/scalyc/0.1.0/scalyc/compiler/Planner.scaly', 'not_implemented', 167, 'method_name', None),
        ('packages/scalyc/0.1.0/scalyc/compiler/Planner.scaly', 'not_implemented_operand', 180, 'method_name', None),
    ],
)
