#!/bin/bash
# Install `scalyc` into a bin dir so it runs from ANY directory — no need to
# `export PATH="$PWD/scalyc/build:$PATH"` or to cd into the repo first.
#
# What it installs: a tiny wrapper named `scalyc` (NOT a copy of the binary)
# that
#   - sets SCALY_HOME to this repo so the compiler finds the prelude and the
#     stdlib packages no matter the current directory (the compiler resolves
#     `packages/` relative to SCALY_HOME when set, else relative to cwd);
#   - makes sure the runtime archive /tmp/libscaly.a exists (it lives in /tmp,
#     which is cleared on reboot), rebuilding it from this repo if missing;
#   - exec's the real compiler at <repo>/scalyc/build/scalyc.
# Because the wrapper points at the in-repo binary, `tools/build-from-seed.sh`
# (or any rebuild) is picked up automatically — no reinstall needed.
#
# Default bin dir is /usr/local/bin, which is on the default PATH on both macOS
# and Linux. Writing there usually needs sudo; the script uses sudo only when
# the dir is not writable. Override the location with BINDIR.
#
# Usage:
#   tools/install.sh                 # -> /usr/local/bin/scalyc
#   BINDIR="$HOME/.local/bin" tools/install.sh
#
# Uninstall: remove the wrapper, e.g.  sudo rm /usr/local/bin/scalyc
set -e
cd "$(dirname "$0")/.."
REPO=$(pwd)
BINDIR=${BINDIR:-/usr/local/bin}
BIN="$REPO/scalyc/build/scalyc"

# Build the compiler from the committed seed if it isn't present yet. This also
# produces /tmp/libscaly.a. Entirely C++-free (llc + a C compiler).
if [ ! -x "$BIN" ]; then
  echo "install: scalyc/build/scalyc not found — building from seed"
  tools/build-from-seed.sh "$BIN"
fi

WRAPPER="$BINDIR/scalyc"
TMP=$(mktemp)
cat > "$TMP" <<EOF
#!/bin/sh
# Auto-generated by tools/install.sh — do not edit by hand.
# Wrapper for the Scaly compiler installed from:
#   $REPO
# Respects a pre-set SCALY_HOME (e.g. to point at a different checkout).
export SCALY_HOME="\${SCALY_HOME:-$REPO}"

# The runtime archive lives at a fixed path the compiler bakes in; /tmp is
# cleared on reboot, so rebuild it from the seed-built compiler if it is gone.
if [ ! -f /tmp/libscaly.a ]; then
    "\$SCALY_HOME/scalyc/build/scalyc" -c --no-prelude --no-tests \\
        -o /tmp/libscaly.o "\$SCALY_HOME/packages/scaly/0.1.0/scaly.scaly" >/dev/null 2>&1 \\
        && ar rcs /tmp/libscaly.a /tmp/libscaly.o
fi

exec "\$SCALY_HOME/scalyc/build/scalyc" "\$@"
EOF
chmod 755 "$TMP"

mkdir -p "$BINDIR" 2>/dev/null || true
if [ -w "$BINDIR" ]; then
  mv "$TMP" "$WRAPPER"
else
  echo "install: $BINDIR is not writable — elevating with sudo"
  sudo mv "$TMP" "$WRAPPER"
fi

echo "install: OK -> $WRAPPER"
echo "         SCALY_HOME=$REPO"

# PATH hint, only when the chosen dir is not already reachable.
case ":$PATH:" in
  *":$BINDIR:"*) echo "         $BINDIR is on your PATH — run 'scalyc' from anywhere." ;;
  *) echo "         NOTE: $BINDIR is NOT on your PATH; add it, or re-run with BINDIR set to a dir that is." ;;
esac
