#!/bin/bash
# Install `scalyc` (and beside it `scaly` and `scalyls`) into a bin dir so it runs from ANY directory — no need to
# `export PATH="$PWD/scalyc/build:$PATH"` or to cd into the repo first.
#
# What it installs: a tiny wrapper named `scalyc` (NOT a copy of the binary)
# that
#   - sets SCALY_HOME to this repo so the compiler finds the prelude and the
#     stdlib packages no matter the current directory (the compiler resolves
#     `packages/` relative to SCALY_HOME when set, else relative to cwd);
#   - makes sure the runtime archive /tmp/libscaly.a exists (it lives in /tmp,
#     which is cleared on reboot), rebuilding it from this repo if missing;
#   - exec's the real compiler at <repo>/scalyc/build/scalyc.
# Because the wrapper points at the in-repo binary, `tools/build-from-seed.sh`
# (or any rebuild) is picked up automatically — no reinstall needed.
#
# Default bin dir is /usr/local/bin, which is on the default PATH on both macOS
# and Linux. Writing there usually needs sudo; the script uses sudo only when
# the dir is not writable. Override the location with BINDIR.
#
# Usage:
#   tools/install.sh                 # -> /usr/local/bin/scalyc
#   BINDIR="$HOME/.local/bin" tools/install.sh
#
# Uninstall: tools/uninstall.sh (same BINDIR override).
set -e
cd "$(dirname "$0")/.."
REPO=$(pwd)
BINDIR=${BINDIR:-/usr/local/bin}
BIN="$REPO/scalyc/build/scalyc"

# Build the compiler from the committed seed if it isn't present yet.
# Entirely C++-free (llc + a C compiler).
if [ ! -x "$BIN" ]; then
  echo "install: scalyc/build/scalyc not found — building from seed"
  tools/build-from-seed.sh "$BIN"
fi

# Build the runtime archive into a PERSISTENT location ($REPO/lib) so it
# survives reboots. The compiler links $SCALY_HOME/lib/libscaly.a when
# SCALY_HOME is set (the wrapper sets it), instead of the ephemeral
# /tmp/libscaly.a. Rebuilt fresh here so it matches the just-built compiler.
echo "install: building runtime archive lib/libscaly.a"
mkdir -p "$REPO/lib"
"$BIN" -c --no-prelude --no-tests -o "$REPO/lib/libscaly.o" \
    "$REPO/packages/scaly/0.1.0/scaly.scaly"
tools/fcontext.sh "$REPO/lib/fcontext.o"
tools/eio.sh "$REPO/lib/eio.o"
tools/ctime.sh "$REPO/lib/ctime.o"
tools/panic.sh "$REPO/lib/panic.o"
rm -f "$REPO/lib/libscaly.a"
ar rcs "$REPO/lib/libscaly.a" "$REPO/lib/libscaly.o" "$REPO/lib/fcontext.o" "$REPO/lib/eio.o" "$REPO/lib/ctime.o" "$REPO/lib/panic.o"

WRAPPER="$BINDIR/scalyc"
TMP=$(mktemp)
cat > "$TMP" <<EOF
#!/bin/sh
# Auto-generated by tools/install.sh — do not edit by hand.
# Wrapper for the Scaly compiler installed from:
#   $REPO
# Respects a pre-set SCALY_HOME (e.g. to point at a different checkout).
export SCALY_HOME="\${SCALY_HOME:-$REPO}"

# The compiler links \$SCALY_HOME/lib/libscaly.a (a persistent path that
# survives reboots). install.sh builds it; rebuild here as a safety net if it
# is ever missing.
if [ ! -f "\$SCALY_HOME/lib/libscaly.a" ]; then
    "\$SCALY_HOME/scalyc/build/scalyc" -c --no-prelude --no-tests \\
        -o "\$SCALY_HOME/lib/libscaly.o" "\$SCALY_HOME/packages/scaly/0.1.0/scaly.scaly" >/dev/null 2>&1 \\
        && "\$SCALY_HOME/tools/fcontext.sh" "\$SCALY_HOME/lib/fcontext.o" >/dev/null 2>&1 \\
        && "\$SCALY_HOME/tools/eio.sh" "\$SCALY_HOME/lib/eio.o" >/dev/null 2>&1 \\
        && "\$SCALY_HOME/tools/ctime.sh" "\$SCALY_HOME/lib/ctime.o" >/dev/null 2>&1 \\
        && "\$SCALY_HOME/tools/panic.sh" "\$SCALY_HOME/lib/panic.o" >/dev/null 2>&1 \\
        && ar rcs "\$SCALY_HOME/lib/libscaly.a" "\$SCALY_HOME/lib/libscaly.o" "\$SCALY_HOME/lib/fcontext.o" "\$SCALY_HOME/lib/eio.o" "\$SCALY_HOME/lib/ctime.o" "\$SCALY_HOME/lib/panic.o"
fi

exec "\$SCALY_HOME/scalyc/build/scalyc" "\$@"
EOF
chmod 755 "$TMP"

mkdir -p "$BINDIR" 2>/dev/null || true
if [ -w "$BINDIR" ]; then
  mv "$TMP" "$WRAPPER"
else
  echo "install: $BINDIR is not writable — elevating with sudo"
  sudo mv "$TMP" "$WRAPPER"
fi

echo "install: OK -> $WRAPPER"
echo "         SCALY_HOME=$REPO"

# Matching wrappers for the two programs tools/build-from-seed.sh builds beside
# the compiler: scaly, the tool (REPL, run, build, test), and scalyls, the
# language server the VS Code extension launches from PATH.
for NAME in scaly scalyls; do
  [ -x "$REPO/scalyc/build/$NAME" ] || continue
  OTHER="$BINDIR/$NAME"
  TMP=$(mktemp)
  cat > "$TMP" <<EOF
#!/bin/sh
# Auto-generated by tools/install.sh — do not edit by hand.
# Wrapper for $NAME installed from:
#   $REPO
export SCALY_HOME="\${SCALY_HOME:-$REPO}"
exec "\$SCALY_HOME/scalyc/build/$NAME" "\$@"
EOF
  chmod 755 "$TMP"
  if [ -w "$BINDIR" ]; then
    mv "$TMP" "$OTHER"
  else
    sudo mv "$TMP" "$OTHER"
  fi
  echo "install: OK -> $OTHER"
done

# PATH hint, only when the chosen dir is not already reachable.
case ":$PATH:" in
  *":$BINDIR:"*) echo "         $BINDIR is on your PATH — run 'scaly' and 'scalyc' from anywhere." ;;
  *) echo "         NOTE: $BINDIR is NOT on your PATH; add it, or re-run with BINDIR set to a dir that is." ;;
esac
