#!/bin/bash
# Undo tools/install.sh: remove the `scalyc` wrapper from the bin dir and delete
# the runtime archive the installer built. The compiler sources and the in-repo
# build (scalyc/build/scalyc) are left untouched — this only reverses `install`.
#
# Usage:
#   tools/uninstall.sh
#   BINDIR=/path tools/uninstall.sh    # same override as install.sh (default /usr/local/bin)
#   FORCE=1     tools/uninstall.sh     # remove BINDIR/scalyc even if it does not
#                                      # look like our generated wrapper
#
# Removing from /usr/local/bin needs write access; sudo is used only when the
# bin dir is not writable.
set -e
cd "$(dirname "$0")/.."
REPO=$(pwd)
BINDIR=${BINDIR:-/usr/local/bin}
WRAPPER="$BINDIR/scalyc"
MARKER="Auto-generated by tools/install.sh"

# rm a file, elevating with sudo only if its directory is not writable.
rm_path() {
  if [ -w "$(dirname "$1")" ]; then
    rm -f "$1"
  else
    echo "uninstall: $(dirname "$1") not writable — elevating with sudo"
    sudo rm -f "$1"
  fi
}

if [ -e "$WRAPPER" ]; then
  if [ "$FORCE" = "1" ] || grep -q "$MARKER" "$WRAPPER" 2>/dev/null; then
    rm_path "$WRAPPER"
    echo "uninstall: removed $WRAPPER"
  else
    echo "uninstall: $WRAPPER exists but is not our generated wrapper — leaving it."
    echo "           (re-run with FORCE=1 to remove it anyway)"
  fi
else
  echo "uninstall: no wrapper at $WRAPPER"
fi

# Same for the scalyls language-server wrapper, when installed.
LSWRAPPER="$BINDIR/scalyls"
if [ -e "$LSWRAPPER" ]; then
  if [ "$FORCE" = "1" ] || grep -q "$MARKER" "$LSWRAPPER" 2>/dev/null; then
    rm_path "$LSWRAPPER"
    echo "uninstall: removed $LSWRAPPER"
  fi
fi

# If some OTHER scalyc is still first on PATH, say so — the user may have a
# second install or a stale copy in a different bin dir.
other=$(command -v scalyc 2>/dev/null || true)
if [ -n "$other" ]; then
  echo "uninstall: NOTE — 'scalyc' still resolves to $other"
fi

# Drop the runtime archive the installer built (cheap to rebuild; reinstalling
# or a direct build recreates it).
for f in "$REPO/lib/libscaly.a" "$REPO/lib/libscaly.o" "$REPO/lib/fcontext.o"; do
  if [ -e "$f" ]; then
    rm -f "$f"
    echo "uninstall: removed $f"
  fi
done
rmdir "$REPO/lib" 2>/dev/null || true

# Best-effort: also clear the ephemeral /tmp archive a non-installed build uses.
rm -f /tmp/libscaly.a /tmp/libscaly.o /tmp/fcontext.o 2>/dev/null || true

echo "uninstall: done — scalyc/build/scalyc and the source tree are untouched."
